// Auto-generated by scripts/generate-segment-specs.mjs.
// Do not edit by hand — re-run the generator instead.
import { ComponentSpec } from "@/hl7/metadata/types";

export type { HL7_AD } from "@/hl7/metadata/datatypes/ad";
export type { HL7_AUI } from "@/hl7/metadata/datatypes/aui";
export type { HL7_CCD } from "@/hl7/metadata/datatypes/ccd";
export type { HL7_CCP } from "@/hl7/metadata/datatypes/ccp";
export type { HL7_CD } from "@/hl7/metadata/datatypes/cd";
export type { HL7_CE } from "@/hl7/metadata/datatypes/ce";
export type { HL7_CF } from "@/hl7/metadata/datatypes/cf";
export type { HL7_CK } from "@/hl7/metadata/datatypes/ck";
export type { HL7_CM_ABS_RANGE } from "@/hl7/metadata/datatypes/cm_abs_range";
export type { HL7_CM_AUI } from "@/hl7/metadata/datatypes/cm_aui";
export type { HL7_CM_BATCH_TOTAL } from "@/hl7/metadata/datatypes/cm_batch_total";
export type { HL7_CM_CCD } from "@/hl7/metadata/datatypes/cm_ccd";
export type { HL7_CM_CCP } from "@/hl7/metadata/datatypes/cm_ccp";
export type { HL7_CM_CD_ELECTRODE } from "@/hl7/metadata/datatypes/cm_cd_electrode";
export type { HL7_CM_CSU } from "@/hl7/metadata/datatypes/cm_csu";
export type { HL7_CM_DDI } from "@/hl7/metadata/datatypes/cm_ddi";
export type { HL7_CM_DIN } from "@/hl7/metadata/datatypes/cm_din";
export type { HL7_CM_DLD } from "@/hl7/metadata/datatypes/cm_dld";
export type { HL7_CM_DLT } from "@/hl7/metadata/datatypes/cm_dlt";
export type { HL7_CM_DTN } from "@/hl7/metadata/datatypes/cm_dtn";
export type { HL7_CM_EIP } from "@/hl7/metadata/datatypes/cm_eip";
export type { HL7_CM_ELD } from "@/hl7/metadata/datatypes/cm_eld";
export type { HL7_CM_FILLER } from "@/hl7/metadata/datatypes/cm_filler";
export type { HL7_CM_FINANCE } from "@/hl7/metadata/datatypes/cm_finance";
export type { HL7_CM_GROUP_ID } from "@/hl7/metadata/datatypes/cm_group_id";
export type { HL7_CM_INTERNAL_LOCATION } from "@/hl7/metadata/datatypes/cm_internal_location";
export type { HL7_CM_JOB_CODE } from "@/hl7/metadata/datatypes/cm_job_code";
export type { HL7_CM_LA1 } from "@/hl7/metadata/datatypes/cm_la1";
export type { HL7_CM_LICENSE_NO } from "@/hl7/metadata/datatypes/cm_license_no";
export type { HL7_CM_MDV } from "@/hl7/metadata/datatypes/cm_mdv";
export type { HL7_CM_MOC } from "@/hl7/metadata/datatypes/cm_moc";
export type { HL7_CM_MSG } from "@/hl7/metadata/datatypes/cm_msg";
export type { HL7_CM_NDL } from "@/hl7/metadata/datatypes/cm_ndl";
export type { HL7_CM_OCD } from "@/hl7/metadata/datatypes/cm_ocd";
export type { HL7_CM_OSD } from "@/hl7/metadata/datatypes/cm_osd";
export type { HL7_CM_OSP } from "@/hl7/metadata/datatypes/cm_osp";
export type { HL7_CM_PAT_ID } from "@/hl7/metadata/datatypes/cm_pat_id";
export type { HL7_CM_PAT_ID_0192 } from "@/hl7/metadata/datatypes/cm_pat_id_0192";
export type { HL7_CM_PCF } from "@/hl7/metadata/datatypes/cm_pcf";
export type { HL7_CM_PEN } from "@/hl7/metadata/datatypes/cm_pen";
export type { HL7_CM_PI } from "@/hl7/metadata/datatypes/cm_pi";
export type { HL7_CM_PIP } from "@/hl7/metadata/datatypes/cm_pip";
export type { HL7_CM_PLACER } from "@/hl7/metadata/datatypes/cm_placer";
export type { HL7_CM_PLN } from "@/hl7/metadata/datatypes/cm_pln";
export type { HL7_CM_POSITION } from "@/hl7/metadata/datatypes/cm_position";
export type { HL7_CM_PRACTITIONER } from "@/hl7/metadata/datatypes/cm_practitioner";
export type { HL7_CM_PRL } from "@/hl7/metadata/datatypes/cm_prl";
export type { HL7_CM_PTA } from "@/hl7/metadata/datatypes/cm_pta";
export type { HL7_CM_RANGE } from "@/hl7/metadata/datatypes/cm_range";
export type { HL7_CM_RFR } from "@/hl7/metadata/datatypes/cm_rfr";
export type { HL7_CM_RI } from "@/hl7/metadata/datatypes/cm_ri";
export type { HL7_CM_RMC } from "@/hl7/metadata/datatypes/cm_rmc";
export type { HL7_CM_SPD } from "@/hl7/metadata/datatypes/cm_spd";
export type { HL7_CM_SPS } from "@/hl7/metadata/datatypes/cm_sps";
export type { HL7_CM_UVC } from "@/hl7/metadata/datatypes/cm_uvc";
export type { HL7_CM_VR } from "@/hl7/metadata/datatypes/cm_vr";
export type { HL7_CM_WVI } from "@/hl7/metadata/datatypes/cm_wvi";
export type { HL7_CN } from "@/hl7/metadata/datatypes/cn";
export type { HL7_CNE } from "@/hl7/metadata/datatypes/cne";
export type { HL7_CNN } from "@/hl7/metadata/datatypes/cnn";
export type { HL7_CN_PERSON } from "@/hl7/metadata/datatypes/cn_person";
export type { HL7_CN_PHYSICIAN } from "@/hl7/metadata/datatypes/cn_physician";
export type { HL7_CP } from "@/hl7/metadata/datatypes/cp";
export type { HL7_CQ } from "@/hl7/metadata/datatypes/cq";
export type { HL7_CSU } from "@/hl7/metadata/datatypes/csu";
export type { HL7_CWE } from "@/hl7/metadata/datatypes/cwe";
export type { HL7_CX } from "@/hl7/metadata/datatypes/cx";
export type { HL7_DDI } from "@/hl7/metadata/datatypes/ddi";
export type { HL7_DIN } from "@/hl7/metadata/datatypes/din";
export type { HL7_DLD } from "@/hl7/metadata/datatypes/dld";
export type { HL7_DLN } from "@/hl7/metadata/datatypes/dln";
export type { HL7_DLT } from "@/hl7/metadata/datatypes/dlt";
export type { HL7_DR } from "@/hl7/metadata/datatypes/dr";
export type { HL7_DTN } from "@/hl7/metadata/datatypes/dtn";
export type { HL7_ED } from "@/hl7/metadata/datatypes/ed";
export type { HL7_EI } from "@/hl7/metadata/datatypes/ei";
export type { HL7_EIP } from "@/hl7/metadata/datatypes/eip";
export type { HL7_ELD } from "@/hl7/metadata/datatypes/eld";
export type { HL7_ERL } from "@/hl7/metadata/datatypes/erl";
export type { HL7_FC } from "@/hl7/metadata/datatypes/fc";
export type { HL7_FN } from "@/hl7/metadata/datatypes/fn";
export type { HL7_HD } from "@/hl7/metadata/datatypes/hd";
export type { HL7_ICD } from "@/hl7/metadata/datatypes/icd";
export type { HL7_JCC } from "@/hl7/metadata/datatypes/jcc";
export type { HL7_LA1 } from "@/hl7/metadata/datatypes/la1";
export type { HL7_LA2 } from "@/hl7/metadata/datatypes/la2";
export type { HL7_MA } from "@/hl7/metadata/datatypes/ma";
export type { HL7_MO } from "@/hl7/metadata/datatypes/mo";
export type { HL7_MOC } from "@/hl7/metadata/datatypes/moc";
export type { HL7_MOP } from "@/hl7/metadata/datatypes/mop";
export type { HL7_MSG } from "@/hl7/metadata/datatypes/msg";
export type { HL7_NA } from "@/hl7/metadata/datatypes/na";
export type { HL7_NDL } from "@/hl7/metadata/datatypes/ndl";
export type { HL7_NR } from "@/hl7/metadata/datatypes/nr";
export type { HL7_OCD } from "@/hl7/metadata/datatypes/ocd";
export type { HL7_OSD } from "@/hl7/metadata/datatypes/osd";
export type { HL7_OSP } from "@/hl7/metadata/datatypes/osp";
export type { HL7_PCF } from "@/hl7/metadata/datatypes/pcf";
export type { HL7_PI } from "@/hl7/metadata/datatypes/pi";
export type { HL7_PIP } from "@/hl7/metadata/datatypes/pip";
export type { HL7_PL } from "@/hl7/metadata/datatypes/pl";
export type { HL7_PLN } from "@/hl7/metadata/datatypes/pln";
export type { HL7_PN } from "@/hl7/metadata/datatypes/pn";
export type { HL7_PPN } from "@/hl7/metadata/datatypes/ppn";
export type { HL7_PRL } from "@/hl7/metadata/datatypes/prl";
export type { HL7_PT } from "@/hl7/metadata/datatypes/pt";
export type { HL7_PTA } from "@/hl7/metadata/datatypes/pta";
export type { HL7_PTS } from "@/hl7/metadata/datatypes/pts";
export type { HL7_QIP } from "@/hl7/metadata/datatypes/qip";
export type { HL7_QSC } from "@/hl7/metadata/datatypes/qsc";
export type { HL7_RCD } from "@/hl7/metadata/datatypes/rcd";
export type { HL7_RFR } from "@/hl7/metadata/datatypes/rfr";
export type { HL7_RI } from "@/hl7/metadata/datatypes/ri";
export type { HL7_RMC } from "@/hl7/metadata/datatypes/rmc";
export type { HL7_RP } from "@/hl7/metadata/datatypes/rp";
export type { HL7_RPT } from "@/hl7/metadata/datatypes/rpt";
export type { HL7_SAD } from "@/hl7/metadata/datatypes/sad";
export type { HL7_SCV } from "@/hl7/metadata/datatypes/scv";
export type { HL7_SN } from "@/hl7/metadata/datatypes/sn";
export type { HL7_SPD } from "@/hl7/metadata/datatypes/spd";
export type { HL7_SPS } from "@/hl7/metadata/datatypes/sps";
export type { HL7_SRT } from "@/hl7/metadata/datatypes/srt";
export type { HL7_TQ } from "@/hl7/metadata/datatypes/tq";
export type { HL7_TS } from "@/hl7/metadata/datatypes/ts";
export type { HL7_UVC } from "@/hl7/metadata/datatypes/uvc";
export type { HL7_VH } from "@/hl7/metadata/datatypes/vh";
export type { HL7_VID } from "@/hl7/metadata/datatypes/vid";
export type { HL7_VR } from "@/hl7/metadata/datatypes/vr";
export type { HL7_WVI } from "@/hl7/metadata/datatypes/wvi";
export type { HL7_WVS } from "@/hl7/metadata/datatypes/wvs";
export type { HL7_XAD } from "@/hl7/metadata/datatypes/xad";
export type { HL7_XCN } from "@/hl7/metadata/datatypes/xcn";
export type { HL7_XON } from "@/hl7/metadata/datatypes/xon";
export type { HL7_XPN } from "@/hl7/metadata/datatypes/xpn";
export type { HL7_XTN } from "@/hl7/metadata/datatypes/xtn";

/**
 * Sub-component layout for every composite HL7 data type, keyed by
 * uppercase id (e.g. `"XAD"`, `"XPN"`, `"CWE"`). Used by the runtime
 * composer to validate and assemble `^`-delimited composite values.
 *
 * Components are taken from the version with the largest set, since
 * composite types only ever grow (added components never break older
 * positions).
 *
 * @since 4.0.0
 */
export const DATA_TYPES: Readonly<Record<string, readonly ComponentSpec[]>> = {
  AD: [
    { num: 1, name: "Street Address", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Other Designation", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "City", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "State Or Province", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Zip Or Postal Code", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 6, name: "Country", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 7, name: "Type", hl7Type: "ID", table: 190, usage: "O", rpt: "1" },
    { num: 8, name: "Other Geographic Designation", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  AUI: [
    { num: 1, name: "Authorization Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 3, name: "Source", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CCD: [
    { num: 1, name: "When To Charge Code", hl7Type: "ID", table: 100, usage: "O", rpt: "1" },
    { num: 2, name: "Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  CCP: [
    { num: 1, name: "Channel Calibration Sensitivity Correction Factor", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Channel Calibration Baseline", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Channel Calibration Time Skew", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CD: [
    { num: 1, name: "Channel Identifier", hl7Type: "CM_WVI", usage: "O", rpt: "1" },
    { num: 2, name: "Waveform source", hl7Type: "CM_CD_ELECTRODE", usage: "O", rpt: "1" },
    { num: 3, name: "Channel Sensitivity/units", hl7Type: "CM_CSU", usage: "O", rpt: "1" },
    { num: 4, name: "Calibration Parameters", hl7Type: "CM_CCP", usage: "O", rpt: "1" },
    { num: 5, name: "Sampling Frequency", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 6, name: "Minimum/maximum Data Values", hl7Type: "CM_MDV", usage: "O", rpt: "1" },
  ],
  CE: [
    { num: 1, name: "Identifier", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Name Of Coding System", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Name Of Alternate Coding System", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CF: [
    { num: 1, name: "Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Formatted Text", hl7Type: "FT", usage: "O", rpt: "1" },
    { num: 3, name: "Name Of Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
    { num: 4, name: "Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Alternate Formatted Text", hl7Type: "FT", usage: "O", rpt: "1" },
    { num: 6, name: "Name Of Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
    { num: 7, name: "Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 8, name: "Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 9, name: "Original Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 10, name: "Second Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 11, name: "Second Alternate Formatted Text", hl7Type: "FT", usage: "O", rpt: "1" },
    { num: 12, name: "Name Of Second Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "O", rpt: "1" },
    { num: 13, name: "Second Alternate Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 14, name: "Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 15, name: "Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 16, name: "Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 17, name: "Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 18, name: "Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 19, name: "Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 20, name: "Second Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 21, name: "Second Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 22, name: "Second Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
  ],
  CK: [
    { num: 1, name: "ID Number", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Check Digit", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Code Identifying the Check Digit Scheme Employed ", hl7Type: "ID", table: 61, usage: "O", rpt: "1" },
    { num: 4, name: "Assigning Facility ID", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_ABS_RANGE: [
    { num: 1, name: "Range", hl7Type: "CM_RANGE", usage: "O", rpt: "1" },
    { num: 2, name: "Numeric Change", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Percent Per Change", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 4, name: "Days", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_AUI: [
    { num: 1, name: "Authorization Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 3, name: "Source", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_BATCH_TOTAL: [
    { num: 1, name: "Batch Total 1", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Batch Total 2", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "...", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_CCD: [
    { num: 1, name: "When To Charge", hl7Type: "ID", table: 100, usage: "O", rpt: "1" },
    { num: 2, name: "Date/Time", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  CM_CCP: [
    { num: 1, name: "Sensitivity Correction Factor", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Baseline", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Time Skew", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_CD_ELECTRODE: [
    { num: 1, name: "Source Name 1", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Source Name 2", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_CSU: [
    { num: 1, name: "Sensitivity", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Unit Identifier", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 3, name: "Unit Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Units Name Of Coding System", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Units Alternate Identifier", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 6, name: "Units Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Units Name Of Alternate Coding System", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_DDI: [
    { num: 1, name: "Delay Days", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Amount", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Number Of Days", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_DIN: [
    { num: 1, name: "Date", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 2, name: "Institution Name", hl7Type: "CE", usage: "O", rpt: "1" },
  ],
  CM_DLD: [
    { num: 1, name: "Code", hl7Type: "ID", table: 113, usage: "O", rpt: "1" },
    { num: 2, name: "Description", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_DLT: [
    { num: 1, name: "Range", hl7Type: "CM_RANGE", usage: "O", rpt: "1" },
    { num: 2, name: "Numeric Threshold", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Change", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Length Of Time-days", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_DTN: [
    { num: 1, name: "Day Type", hl7Type: "ID", table: 149, usage: "O", rpt: "1" },
    { num: 2, name: "Number Of Days", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_EIP: [
    { num: 1, name: "Parent's Placer Order Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Parent's Filler Order Number", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_ELD: [
    { num: 1, name: "Segment-id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Sequence", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Field-position", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 4, name: "Code Identifying Error", hl7Type: "CE", table: 60, usage: "O", rpt: "1" },
  ],
  CM_FILLER: [
    { num: 1, name: "Unique Filler Id", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Filler Application Id", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_FINANCE: [
    { num: 1, name: "Financial Class Id", hl7Type: "ID", table: 64, usage: "O", rpt: "1" },
    { num: 2, name: "Effective Date", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  CM_GROUP_ID: [
    { num: 1, name: "Unique Group Id", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Placer Application Id", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_INTERNAL_LOCATION: [
    { num: 1, name: "Nurse Unit (station)", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Room", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 3, name: "Bed", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 4, name: "Facility Id", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 5, name: "Bed Status", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_JOB_CODE: [
    { num: 1, name: "Job Code", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Employee Classification", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_LA1: [
    { num: 1, name: "Dispense / Deliver To Location", hl7Type: "CM_INTERNAL_LOCATION", usage: "O", rpt: "1" },
    { num: 2, name: "Location", hl7Type: "AD", usage: "O", rpt: "1" },
  ],
  CM_LICENSE_NO: [
    { num: 1, name: "License Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Issuing State,province,country", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_MDV: [
    { num: 1, name: "Minimum Value", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Maximum Value", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_MOC: [
    { num: 1, name: "Dollar Amount", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Charge Code", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_MSG: [
    { num: 1, name: "Message Type", hl7Type: "ID", table: 76, usage: "O", rpt: "1" },
    { num: 2, name: "Trigger Event", hl7Type: "ID", table: 3, usage: "O", rpt: "1" },
  ],
  CM_NDL: [
    { num: 1, name: "OP Name", hl7Type: "CN", usage: "O", rpt: "1" },
    { num: 2, name: "Start Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 3, name: "End Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 4, name: "Point Of Care", hl7Type: "IS", table: 302, usage: "O", rpt: "1" },
    { num: 5, name: "Room", hl7Type: "IS", table: 303, usage: "O", rpt: "1" },
    { num: 6, name: "Bed", hl7Type: "IS", table: 304, usage: "O", rpt: "1" },
    { num: 7, name: "Facility", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 8, name: "Location Status", hl7Type: "IS", table: 306, usage: "O", rpt: "1" },
    { num: 9, name: "Person Location Type", hl7Type: "IS", table: 305, usage: "O", rpt: "1" },
    { num: 10, name: "Building", hl7Type: "IS", table: 307, usage: "O", rpt: "1" },
    { num: 11, name: "Floor", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_OCD: [
    { num: 1, name: "Occurrence Code", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Occurrence Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  CM_OSD: [
    { num: 1, name: "Sequence/results Flag", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Placer Order Number Entity Identifier", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 3, name: "Placer Order Number Namespace ID", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 4, name: "Filler Order Number Entity Identifier", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 5, name: "Filler Order Number Namespace ID", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 6, name: "Sequence Condition Value", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Maximum Number Of Repeats", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 8, name: "Placer Order Number Universal ID", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 9, name: "Placer Order Number Universal ID Type", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 10, name: "Filler Order Number Universal ID", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 11, name: "Filler Order Number Universal ID Type", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_OSP: [
    { num: 1, name: "Occurrence Span Code", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Occurrence Span Start Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 3, name: "Occurrence Span Stop Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  CM_PAT_ID: [
    { num: 1, name: "Patient Id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Check Digit", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Check Digit Scheme", hl7Type: "ID", table: 61, usage: "O", rpt: "1" },
    { num: 4, name: "Facility Id", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 5, name: "Type", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_PAT_ID_0192: [
    { num: 1, name: "Patient Id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Check Digit", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Check Digit Scheme", hl7Type: "ID", table: 61, usage: "O", rpt: "1" },
    { num: 4, name: "Facility Id", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 5, name: "Type", hl7Type: "ID", table: 192, usage: "O", rpt: "1" },
  ],
  CM_PCF: [
    { num: 1, name: "Pre-certification Patient Type", hl7Type: "ID", table: 150, usage: "O", rpt: "1" },
    { num: 2, name: "Pre-certication Required", hl7Type: "ID", table: 136, usage: "O", rpt: "1" },
    { num: 3, name: "Pre-certification Window", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  CM_PEN: [
    { num: 1, name: "Penalty Id", hl7Type: "ID", table: 148, usage: "O", rpt: "1" },
    { num: 2, name: "Penalty Amount", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_PI: [
    { num: 1, name: "ID Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Type Of ID Number", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 3, name: "Other Qualifying Info", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_PIP: [
    { num: 1, name: "Privilege", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 2, name: "Privilege Class", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 3, name: "Expiration Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 4, name: "Activation Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  CM_PLACER: [
    { num: 1, name: "Unique Placer Id", hl7Type: "ST", length: { max: 15 }, usage: "O", rpt: "1" },
    { num: 2, name: "Placer Application", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_PLN: [
    { num: 1, name: "ID Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Type Of ID Number", hl7Type: "IS", table: 338, usage: "O", rpt: "1" },
    { num: 3, name: "State/other Qualifying Info", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Expiration Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  CM_POSITION: [
    { num: 1, name: "Hall", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Table", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Chair", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_PRACTITIONER: [
    { num: 1, name: "Procedure Practitioner  Id", hl7Type: "CN_PERSON", usage: "O", rpt: "1" },
    { num: 2, name: "Procedure Practitioner Type", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CM_PRL: [
    { num: 1, name: "OBX-3-observation identifier of parent result", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "OBX-4-sub-ID of parent result", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "OBX-5-observation results from parent", hl7Type: "CE", usage: "O", rpt: "1" },
  ],
  CM_PTA: [
    { num: 1, name: "Policy Type", hl7Type: "ID", table: 147, usage: "O", rpt: "1" },
    { num: 2, name: "Amount Class", hl7Type: "ID", table: 193, usage: "O", rpt: "1" },
    { num: 3, name: "Amount", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_RANGE: [
    { num: 1, name: "Low Value", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "High Value", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_RFR: [
    { num: 1, name: "Reference Range", hl7Type: "CM_RANGE", usage: "O", rpt: "1" },
    { num: 2, name: "Sex", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 3, name: "Age Range", hl7Type: "CM_RANGE", usage: "O", rpt: "1" },
    { num: 4, name: "Gestational Age Range", hl7Type: "CM_RANGE", usage: "O", rpt: "1" },
    { num: 5, name: "Species", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Race / Subspecies", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 7, name: "Text Condition", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_RI: [
    { num: 1, name: "Repeat Pattern", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Explicit Time Intevall", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_RMC: [
    { num: 1, name: "Room Type", hl7Type: "ID", table: 145, usage: "O", rpt: "1" },
    { num: 2, name: "Amount Type", hl7Type: "ID", table: 146, usage: "O", rpt: "1" },
    { num: 3, name: "Coverage Amount", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_SPD: [
    { num: 1, name: "Specialty Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Governing Board", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Eligible Or Certified", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 4, name: "Date Of Certification", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  CM_SPS: [
    { num: 1, name: "Specimen Source Name Or Code", hl7Type: "CE", table: 70, usage: "O", rpt: "1" },
    { num: 2, name: "Additives", hl7Type: "TX", usage: "O", rpt: "1" },
    { num: 3, name: "Freetext", hl7Type: "TX", usage: "O", rpt: "1" },
    { num: 4, name: "Body Site", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 5, name: "Site Modifier", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 6, name: "Collection Modifier Method Code", hl7Type: "CE", usage: "O", rpt: "1" },
  ],
  CM_UVC: [
    { num: 1, name: "Value Code", hl7Type: "ID", table: 153, usage: "O", rpt: "1" },
    { num: 2, name: "Value Amount", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  CM_VR: [
    { num: 1, name: "First Data Code Value", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Last Data Code Calue", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CM_WVI: [
    { num: 1, name: "Channel Number", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Channel Name", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CN: [
    { num: 1, name: "ID Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Family Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Middle Initial Or Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Suffix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Prefix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Degree", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 8, name: "Source Table", hl7Type: "ID", table: 297, usage: "O", rpt: "1" },
    { num: 9, name: "Assigning Authority", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CNE: [
    { num: 1, name: "Identifier", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 2, name: "Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Name Of Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "O", rpt: "1" },
    { num: 4, name: "Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Name Of Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "O", rpt: "1" },
    { num: 7, name: "Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 8, name: "Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 9, name: "Original Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 10, name: "Second Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 11, name: "Second Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 12, name: "Name Of Second Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "O", rpt: "1" },
    { num: 13, name: "Second Alternate Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 14, name: "Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 15, name: "Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 16, name: "Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 17, name: "Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 18, name: "Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 19, name: "Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 20, name: "Second Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 21, name: "Second Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 22, name: "Second Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
  ],
  CNN: [
    { num: 1, name: "ID Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Family Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Second And Further Given Names Or Initials Thereof", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Suffix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Prefix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Degree", hl7Type: "IS", table: 360, usage: "O", rpt: "1" },
    { num: 8, name: "Source Table", hl7Type: "IS", table: 297, usage: "O", rpt: "1" },
    { num: 9, name: "Assigning Authority Namespace ID", hl7Type: "IS", table: 363, usage: "O", rpt: "1" },
    { num: 10, name: "Assigning Authority Universal ID", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 11, name: "Assigning Authority Universal ID Type", hl7Type: "ID", table: 301, usage: "O", rpt: "1" },
  ],
  CN_PERSON: [
    { num: 1, name: "Id Number", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Familiy Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Middle Initial Or Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Suffix (e.g. Jr Or Iii)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Prefix (e.g. Dr)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Degree (e.g. Md)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 8, name: "Source Table Id", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CN_PHYSICIAN: [
    { num: 1, name: "Physician Id", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 2, name: "Familiy Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Middle Initial Or Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Suffix (e.g. Jr Or Iii)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Prefix (e.g. Dr)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Degree (e.g. Md)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 8, name: "Source Table Id", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CP: [
    { num: 1, name: "Price", hl7Type: "MO", usage: "O", rpt: "1" },
    { num: 2, name: "Price Type", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 3, name: "From Value", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 4, name: "To Value", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 5, name: "Range Units", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 6, name: "Range Type", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  CQ: [
    { num: 1, name: "Quantity", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Units", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  CSU: [
    { num: 1, name: "Channel Sensitivity", hl7Type: "NM", usage: "R", rpt: "1" },
    { num: 2, name: "Unit Of Measure Identifier", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 3, name: "Unit Of Measure Description", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 4, name: "Unit Of Measure Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
    { num: 5, name: "Alternate Unit Of Measure Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Alternate Unit Of Measure Description", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Alternate Unit Of Measure Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
    { num: 8, name: "Unit Of Measure Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 9, name: "Alternate Unit Of Measure Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 10, name: "Original Text", hl7Type: "ST", length: { max: 199 }, usage: "O", rpt: "1" },
    { num: 11, name: "Second Alternate Unit Of Measure Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 12, name: "Second Alternate Unit Of Measure Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 13, name: "Name Of Second Alternate Unit Of Measure Coding Sy", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "O", rpt: "1" },
    { num: 14, name: "Second Alternate Unit Of Measure Coding System Ver", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 15, name: "Unit Of Measure Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 16, name: "Unit Of Measure Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 17, name: "Unit Of Measure Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 18, name: "Alternate Unit Of Measure Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 19, name: "Alternate Unit Of Measure Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 20, name: "Alternate Unit Of Measure Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 21, name: "Alternate Unit Of Measure Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 22, name: "Alternate Unit Of Measure Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 23, name: "Alternate Unit Of Measure Value Set Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
  ],
  CWE: [
    { num: 1, name: "Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Name Of Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
    { num: 4, name: "Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Name Of Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
    { num: 7, name: "Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 8, name: "Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 9, name: "Original Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 10, name: "Second Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 11, name: "Second Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 12, name: "Name Of Second Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
    { num: 13, name: "Second Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 14, name: "Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 15, name: "Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 16, name: "Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 17, name: "Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 18, name: "Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 19, name: "Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
    { num: 20, name: "Second Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 21, name: "Second Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 22, name: "Second Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
  ],
  CX: [
    { num: 1, name: "Id Number", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 2, name: "Identifier Check Digit", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Check Digit Scheme", hl7Type: "ID", length: { max: 3 }, table: 61, usage: "O", rpt: "1" },
    { num: 4, name: "Assigning Authority", hl7Type: "HD", table: 363, usage: "D", rpt: "1" },
    { num: 5, name: "Identifier Type Code", hl7Type: "ID", length: { max: 5 }, table: 203, usage: "R", rpt: "1" },
    { num: 6, name: "Assigning Facility", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 7, name: "Effective Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 8, name: "Expiration Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 9, name: "Assigning Jurisdiction", hl7Type: "CWE", usage: "D", rpt: "1" },
    { num: 10, name: "Assigning Agency Or Department", hl7Type: "CWE", usage: "D", rpt: "1" },
    { num: 11, name: "Security Check", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 12, name: "Security Check Scheme", hl7Type: "ID", length: { max: 3 }, table: 904, usage: "O", rpt: "1" },
  ],
  DDI: [
    { num: 1, name: "Delay Days", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Amount", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Number Of Days", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  DIN: [
    { num: 1, name: "Date", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 2, name: "Institution Name", hl7Type: "CE", usage: "O", rpt: "1" },
  ],
  DLD: [
    { num: 1, name: "Discharge Location", hl7Type: "IS", table: 113, usage: "O", rpt: "1" },
    { num: 2, name: "Effective Date", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  DLN: [
    { num: 1, name: "Driver s License Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Issuing State, Province, Country", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 3, name: "Expiration Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  DLT: [
    { num: 1, name: "Range", hl7Type: "NR", usage: "O", rpt: "1" },
    { num: 2, name: "Numeric Threshold", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Change Computation", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Length Of Time-days", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  DR: [
    { num: 1, name: "Range Start Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 2, name: "Range End Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  DTN: [
    { num: 1, name: "Day Type", hl7Type: "IS", table: 149, usage: "O", rpt: "1" },
    { num: 2, name: "Number Of Days", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  ED: [
    { num: 1, name: "Source Application", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 2, name: "Type Of Data", hl7Type: "ID", table: 191, usage: "O", rpt: "1" },
    { num: 3, name: "Data Subtype", hl7Type: "ID", table: 291, usage: "O", rpt: "1" },
    { num: 4, name: "Encoding", hl7Type: "ID", table: 299, usage: "O", rpt: "1" },
    { num: 5, name: "Data", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  EI: [
    { num: 1, name: "Entity Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Namespace ID", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 3, name: "Universal ID", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Universal ID Type", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  EIP: [
    { num: 1, name: "Parent s Placer Order Number", hl7Type: "EI", usage: "O", rpt: "1" },
    { num: 2, name: "Parent s Filler Order Number", hl7Type: "EI", usage: "O", rpt: "1" },
  ],
  ELD: [
    { num: 1, name: "Segment ID", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Sequence", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Field Position", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 4, name: "Code Identifying Error", hl7Type: "CE", table: 357, usage: "O", rpt: "1" },
  ],
  ERL: [
    { num: 1, name: "Segment Id", hl7Type: "ST", length: { max: 3 }, usage: "R", rpt: "1" },
    { num: 2, name: "Segment Sequence", hl7Type: "NM", length: { max: 2 }, usage: "R", rpt: "1" },
    { num: 3, name: "Field Position", hl7Type: "NM", length: { max: 2 }, usage: "O", rpt: "1" },
    { num: 4, name: "Field Repetition", hl7Type: "NM", length: { max: 2 }, usage: "O", rpt: "1" },
    { num: 5, name: "Component Number", hl7Type: "NM", length: { max: 2 }, usage: "O", rpt: "1" },
    { num: 6, name: "Sub-component Number", hl7Type: "NM", length: { max: 2 }, usage: "O", rpt: "1" },
  ],
  FC: [
    { num: 1, name: "Financial Class", hl7Type: "IS", table: 64, usage: "O", rpt: "1" },
    { num: 2, name: "Effective Date", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  FN: [
    { num: 1, name: "Surname", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Own Surname Prefix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Own Surname", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Surname Prefix From Partner/Spouse", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Surname From Partner/Spouse", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  HD: [
    { num: 1, name: "Namespace ID", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 2, name: "Universal ID", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Universal ID Type", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  ICD: [
    { num: 1, name: "Certification Patient Type", hl7Type: "IS", length: { max: 11 }, table: 150, usage: "O", rpt: "1" },
    { num: 2, name: "Certification Required", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "R", rpt: "1" },
    { num: 3, name: "Date/Time Certification Required", hl7Type: "TS", length: { max: 26 }, usage: "O", rpt: "1" },
  ],
  JCC: [
    { num: 1, name: "Job Code", hl7Type: "IS", length: { max: 20 }, table: 327, usage: "O", rpt: "1" },
    { num: 2, name: "Job Class", hl7Type: "IS", length: { max: 20 }, table: 328, usage: "O", rpt: "1" },
    { num: 3, name: "Job Description Text", hl7Type: "TX", length: { max: 250 }, usage: "O", rpt: "1" },
  ],
  LA1: [
    { num: 1, name: "Point Of Care", hl7Type: "IS", table: 302, usage: "O", rpt: "1" },
    { num: 2, name: "Room", hl7Type: "IS", table: 303, usage: "O", rpt: "1" },
    { num: 3, name: "Bed", hl7Type: "IS", table: 304, usage: "O", rpt: "1" },
    { num: 4, name: "Facility", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 5, name: "Location Status", hl7Type: "IS", table: 306, usage: "O", rpt: "1" },
    { num: 6, name: "Person Location Type", hl7Type: "IS", table: 305, usage: "O", rpt: "1" },
    { num: 7, name: "Building", hl7Type: "IS", table: 307, usage: "O", rpt: "1" },
    { num: 8, name: "Floor", hl7Type: "IS", table: 308, usage: "O", rpt: "1" },
    { num: 9, name: "Address", hl7Type: "AD", usage: "O", rpt: "1" },
  ],
  LA2: [
    { num: 1, name: "Point Of Care", hl7Type: "IS", table: 302, usage: "O", rpt: "1" },
    { num: 2, name: "Room", hl7Type: "IS", table: 303, usage: "O", rpt: "1" },
    { num: 3, name: "Bed", hl7Type: "IS", table: 304, usage: "O", rpt: "1" },
    { num: 4, name: "Facility", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 5, name: "Location Status", hl7Type: "IS", table: 306, usage: "O", rpt: "1" },
    { num: 6, name: "Person Location Type", hl7Type: "IS", table: 305, usage: "O", rpt: "1" },
    { num: 7, name: "Building", hl7Type: "IS", table: 307, usage: "O", rpt: "1" },
    { num: 8, name: "Floor", hl7Type: "IS", table: 308, usage: "O", rpt: "1" },
    { num: 9, name: "Street Address", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 10, name: "Other Designation", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 11, name: "City", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 12, name: "State Or Province", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 13, name: "Zip Or Postal Code", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 14, name: "Country", hl7Type: "ID", usage: "O", rpt: "1" },
    { num: 15, name: "Address Type", hl7Type: "ID", table: 190, usage: "O", rpt: "1" },
    { num: 16, name: "Other Geographic Designation", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  MA: [
    { num: 1, name: "Sample 1 From Channel 1", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Sample 1 From Channel 2", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Sample 1 From Channel 3", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 4, name: "Sample 2 From Channel 1", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 5, name: "Sample 2 From Channel 2", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 6, name: "Sample 2 From Channel 3", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  MO: [
    { num: 1, name: "Quantity", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Denomenation", hl7Type: "ID", usage: "O", rpt: "1" },
  ],
  MOC: [
    { num: 1, name: "Dollar Amount", hl7Type: "MO", usage: "O", rpt: "1" },
    { num: 2, name: "Charge Code", hl7Type: "CE", usage: "O", rpt: "1" },
  ],
  MOP: [
    { num: 1, name: "Money Or Percentage Indicator", hl7Type: "ID", length: { max: 2 }, table: 148, usage: "R", rpt: "1" },
    { num: 2, name: "Money Or Percentage Quantity", hl7Type: "NM", length: { max: 16 }, usage: "R", rpt: "1" },
    { num: 3, name: "Currency Denomination", hl7Type: "ID", length: { max: 3 }, usage: "O", rpt: "1" },
  ],
  MSG: [
    { num: 1, name: "Message Type", hl7Type: "ID", table: 76, usage: "O", rpt: "1" },
    { num: 2, name: "Trigger Event", hl7Type: "ID", table: 3, usage: "O", rpt: "1" },
    { num: 3, name: "Message Structure", hl7Type: "ID", table: 354, usage: "O", rpt: "1" },
  ],
  NA: [
    { num: 1, name: "Value1", hl7Type: "NM", length: { max: 16 }, usage: "R", rpt: "1" },
    { num: 2, name: "Value2", hl7Type: "NM", length: { max: 16 }, usage: "O", rpt: "1" },
    { num: 3, name: "Value3", hl7Type: "NM", length: { max: 16 }, usage: "O", rpt: "1" },
    { num: 4, name: "Value4", hl7Type: "NM", length: { max: 16 }, usage: "O", rpt: "1" },
    { num: 5, name: "Value5", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 6, name: "Value6", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 7, name: "Value7", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 8, name: "Value8", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 9, name: "Value9", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 10, name: "Value10", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  NDL: [
    { num: 1, name: "OP Name", hl7Type: "CN", usage: "O", rpt: "1" },
    { num: 2, name: "Start Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 3, name: "End Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 4, name: "Point Of Care", hl7Type: "IS", table: 302, usage: "O", rpt: "1" },
    { num: 5, name: "Room", hl7Type: "IS", table: 303, usage: "O", rpt: "1" },
    { num: 6, name: "Bed", hl7Type: "IS", table: 304, usage: "O", rpt: "1" },
    { num: 7, name: "Facility", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 8, name: "Location Status", hl7Type: "IS", table: 306, usage: "O", rpt: "1" },
    { num: 9, name: "Person Location Type", hl7Type: "IS", table: 305, usage: "O", rpt: "1" },
    { num: 10, name: "Building", hl7Type: "IS", table: 307, usage: "O", rpt: "1" },
    { num: 11, name: "Floor", hl7Type: "IS", table: 308, usage: "O", rpt: "1" },
  ],
  NR: [
    { num: 1, name: "Low Value", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "High Value", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  OCD: [
    { num: 1, name: "Occurrence Code", hl7Type: "ID", table: 350, usage: "O", rpt: "1" },
    { num: 2, name: "Occurrence Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  OSD: [
    { num: 1, name: "Sequence/results Flag", hl7Type: "ID", usage: "R", rpt: "1" },
    { num: 2, name: "Placer Order Number: Entity Identifier", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 3, name: "Placer Order Number: Namespace ID", hl7Type: "IS", table: 363, usage: "O", rpt: "1" },
    { num: 4, name: "Filler Order Number: Entity Identifier", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 5, name: "Filler Order Number: Namespace ID", hl7Type: "IS", table: 363, usage: "O", rpt: "1" },
    { num: 6, name: "Sequence Condition Value", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 7, name: "Maximum Number Of Repeats", hl7Type: "NM", usage: "R", rpt: "1" },
    { num: 8, name: "Placer Order Number: Universal ID", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 9, name: "Placer Order Number; Universal ID Type", hl7Type: "ID", table: 301, usage: "O", rpt: "1" },
    { num: 10, name: "Filler Order Number: Universal ID", hl7Type: "ST", usage: "R", rpt: "1" },
    { num: 11, name: "Filler Order Number: Universal ID Type", hl7Type: "ID", table: 301, usage: "O", rpt: "1" },
  ],
  OSP: [
    { num: 1, name: "Occurrence Span Code", hl7Type: "CE", table: 351, usage: "O", rpt: "1" },
    { num: 2, name: "Occurrence Span Start Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 3, name: "Occurrence Span Stop Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  PCF: [
    { num: 1, name: "Pre-certification Patient Type", hl7Type: "IS", table: 150, usage: "O", rpt: "1" },
    { num: 2, name: "Pre-certification Required", hl7Type: "ID", table: 136, usage: "O", rpt: "1" },
    { num: 3, name: "Pre-certification Window", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  PI: [
    { num: 1, name: "ID Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Type Of ID Number", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 3, name: "Other Qualifying Info", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  PIP: [
    { num: 1, name: "Privilege", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 2, name: "Privilege Class", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 3, name: "Expiration Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 4, name: "Activation Date", hl7Type: "DT", usage: "O", rpt: "1" },
    { num: 5, name: "Facility", hl7Type: "EI", usage: "O", rpt: "1" },
  ],
  PL: [
    { num: 1, name: "Point Of Care", hl7Type: "IS", length: { max: 20 }, table: 302, usage: "O", rpt: "1" },
    { num: 2, name: "Room", hl7Type: "IS", length: { max: 20 }, table: 303, usage: "O", rpt: "1" },
    { num: 3, name: "Bed", hl7Type: "IS", length: { max: 20 }, table: 304, usage: "O", rpt: "1" },
    { num: 4, name: "Facility", hl7Type: "HD", length: { max: 227 }, usage: "O", rpt: "1" },
    { num: 5, name: "Location Status", hl7Type: "IS", length: { max: 20 }, table: 306, usage: "O", rpt: "1" },
    { num: 6, name: "Person Location Type", hl7Type: "IS", length: { max: 20 }, table: 305, usage: "D", rpt: "1" },
    { num: 7, name: "Building", hl7Type: "IS", length: { max: 20 }, table: 307, usage: "O", rpt: "1" },
    { num: 8, name: "Floor", hl7Type: "IS", length: { max: 20 }, table: 308, usage: "O", rpt: "1" },
    { num: 9, name: "Location Description", hl7Type: "ST", length: { max: 199 }, usage: "O", rpt: "1" },
    { num: 10, name: "Comprehensive Location Identifier", hl7Type: "EI", length: { max: 427 }, usage: "O", rpt: "1" },
    { num: 11, name: "Assigning Authority For Location", hl7Type: "HD", length: { max: 227 }, usage: "O", rpt: "1" },
  ],
  PLN: [
    { num: 1, name: "ID Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Type Of ID Number", hl7Type: "IS", table: 338, usage: "O", rpt: "1" },
    { num: 3, name: "State/other Qualifying Info", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Expiration Date", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  PN: [
    { num: 1, name: "Familiy Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Middle Initial Or Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Suffix (e.g. Jr Or Iii)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Prefix (e.g. Dr)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Degree (e.g. Md)", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  PPN: [
    { num: 1, name: "Person Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Family Name", hl7Type: "FN", usage: "O", rpt: "1" },
    { num: 3, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Second And Further Given Names Or Initials Thereof", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Suffix (e.g., Jr Or Iii)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Prefix (e.g., Dr)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Degree (e.g., Md)", hl7Type: "ST", usage: "W", rpt: "1" },
    { num: 8, name: "Source Table", hl7Type: "CWE", table: 297, usage: "B", rpt: "1" },
    { num: 9, name: "Assigning Authority", hl7Type: "HD", table: 363, usage: "D", rpt: "1" },
    { num: 10, name: "Name Type Code", hl7Type: "ID", length: { max: 5 }, table: 200, usage: "O", rpt: "1" },
    { num: 11, name: "Identifier Check Digit", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 12, name: "Check Digit Scheme", hl7Type: "ID", length: { max: 3 }, table: 61, usage: "D", rpt: "1" },
    { num: 13, name: "Identifier Type Code", hl7Type: "ID", length: { max: 5 }, table: 203, usage: "O", rpt: "1" },
    { num: 14, name: "Assigning Facility", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 15, name: "Date/Time Action Performed", hl7Type: "DTM", usage: "O", rpt: "1" },
    { num: 16, name: "Name Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
    { num: 17, name: "Name Context", hl7Type: "CWE", table: 448, usage: "O", rpt: "1" },
    { num: 18, name: "Name Validity Range", hl7Type: "ST", usage: "W", rpt: "1" },
    { num: 19, name: "Name Assembly Order", hl7Type: "ID", length: { max: 1 }, table: 444, usage: "O", rpt: "1" },
    { num: 20, name: "Effective Date", hl7Type: "DTM", usage: "O", rpt: "1" },
    { num: 21, name: "Expiration Date", hl7Type: "DTM", usage: "O", rpt: "1" },
    { num: 22, name: "Professional Suffix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 23, name: "Assigning Jurisdiction", hl7Type: "CWE", usage: "O", rpt: "1" },
    { num: 24, name: "Assigning Agency Or Department", hl7Type: "CWE", usage: "O", rpt: "1" },
    { num: 25, name: "Security Check", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 26, name: "Security Check Scheme", hl7Type: "ID", length: { max: 3 }, table: 904, usage: "O", rpt: "1" },
  ],
  PRL: [
    { num: 1, name: "OBX-3 Observation Identifier Of Parent Result", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 2, name: "OBX-4 Sub-ID Of Parent Result", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Part Of OBX-5 Observation Result From Parent", hl7Type: "TX", usage: "O", rpt: "1" },
  ],
  PT: [
    { num: 1, name: "Processing ID", hl7Type: "ST", table: 103, usage: "O", rpt: "1" },
    { num: 2, name: "Processing Mode", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  PTA: [
    { num: 1, name: "Policy Type", hl7Type: "IS", length: { max: 5 }, table: 147, usage: "R", rpt: "1" },
    { num: 2, name: "Amount Class", hl7Type: "IS", length: { max: 9 }, table: 193, usage: "O", rpt: "1" },
    { num: 3, name: "Money Or Percentage Quantity", hl7Type: "NM", length: { max: 16 }, usage: "B", rpt: "1" },
    { num: 4, name: "Money Or Percentage", hl7Type: "MOP", length: { max: 23 }, usage: "R", rpt: "1" },
  ],
  PTS: [
    { num: 1, name: "Authentication person", hl7Type: "XCN", usage: "O", rpt: "1" },
    { num: 2, name: "Authentication time stamp", hl7Type: "TS", usage: "O", rpt: "1" },
  ],
  QIP: [
    { num: 1, name: "Field Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Value1&value2&value3", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  QSC: [
    { num: 1, name: "Name Of Field", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Relational Operator", hl7Type: "ID", table: 209, usage: "O", rpt: "1" },
    { num: 3, name: "Value", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Relational Conjunction", hl7Type: "ID", table: 210, usage: "O", rpt: "1" },
  ],
  RCD: [
    { num: 1, name: "HL7 Item Number", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "HL7 Date Type", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Maximum Column Width", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  RFR: [
    { num: 1, name: "Numeric Range", hl7Type: "NR", usage: "O", rpt: "1" },
    { num: 2, name: "Administrative Sex", hl7Type: "IS", table: 1, usage: "O", rpt: "1" },
    { num: 3, name: "Age Range", hl7Type: "NR", usage: "O", rpt: "1" },
    { num: 4, name: "Gestational Age Range", hl7Type: "NR", usage: "O", rpt: "1" },
    { num: 5, name: "Species", hl7Type: "TX", usage: "O", rpt: "1" },
    { num: 6, name: "Race/subspecies", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Conditions", hl7Type: "TX", usage: "O", rpt: "1" },
  ],
  RI: [
    { num: 1, name: "Repeat Pattern", hl7Type: "IS", table: 335, usage: "O", rpt: "1" },
    { num: 2, name: "Explicit Time Interval", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  RMC: [
    { num: 1, name: "Room Type", hl7Type: "IS", length: { max: 20 }, table: 145, usage: "R", rpt: "1" },
    { num: 2, name: "Amount Type", hl7Type: "IS", length: { max: 20 }, table: 146, usage: "O", rpt: "1" },
    { num: 3, name: "Coverage Amount", hl7Type: "NM", length: { max: 16 }, usage: "B", rpt: "1" },
    { num: 4, name: "Money Or Percentage", hl7Type: "MOP", length: { max: 23 }, usage: "R", rpt: "1" },
  ],
  RP: [
    { num: 1, name: "Pointer", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Application ID", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 3, name: "Type Of Data", hl7Type: "ID", table: 191, usage: "O", rpt: "1" },
    { num: 4, name: "Subtype", hl7Type: "ID", table: 291, usage: "O", rpt: "1" },
  ],
  RPT: [
    { num: 1, name: "Repeat Pattern Code", hl7Type: "CWE", length: { max: 705 }, table: 335, usage: "R", rpt: "1" },
    { num: 2, name: "Calendar Alignment", hl7Type: "ID", length: { max: 2 }, table: 527, usage: "O", rpt: "1" },
    { num: 3, name: "Phase Range Begin Value", hl7Type: "NM", length: { max: 10 }, usage: "O", rpt: "1" },
    { num: 4, name: "Phase Range End Value", hl7Type: "NM", length: { max: 10 }, usage: "O", rpt: "1" },
    { num: 5, name: "Period Quantity", hl7Type: "NM", length: { max: 10 }, usage: "O", rpt: "1" },
    { num: 6, name: "Period Units", hl7Type: "IS", length: { max: 10 }, usage: "D", rpt: "1" },
    { num: 7, name: "Institution Specified Time", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "O", rpt: "1" },
    { num: 8, name: "Event", hl7Type: "ID", length: { max: 6 }, table: 528, usage: "O", rpt: "1" },
    { num: 9, name: "Event Offset Quantity", hl7Type: "NM", length: { max: 10 }, usage: "O", rpt: "1" },
    { num: 10, name: "Event Offset Units", hl7Type: "IS", length: { max: 10 }, usage: "D", rpt: "1" },
    { num: 11, name: "General Timing Specification", hl7Type: "GTS", length: { max: 200 }, usage: "O", rpt: "1" },
  ],
  SAD: [
    { num: 1, name: "Street Or Mailing Address", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Street Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Dwelling Number", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  SCV: [
    { num: 1, name: "Parameter Class", hl7Type: "IS", usage: "O", rpt: "1" },
    { num: 2, name: "Parameter Value", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  SN: [
    { num: 1, name: "Comparator", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Num1", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 3, name: "Separator Or Suffix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Num2", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  SPD: [
    { num: 1, name: "Specialty Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Governing Board", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Eligible Or Certified", hl7Type: "ID", table: 337, usage: "O", rpt: "1" },
    { num: 4, name: "Date Of Certification", hl7Type: "DT", usage: "O", rpt: "1" },
  ],
  SPS: [
    { num: 1, name: "Specimen Source Name Or Code", hl7Type: "CE", table: 70, usage: "O", rpt: "1" },
    { num: 2, name: "Additives", hl7Type: "TX", usage: "O", rpt: "1" },
    { num: 3, name: "Freetext", hl7Type: "TX", usage: "O", rpt: "1" },
    { num: 4, name: "Body Site", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 5, name: "Site Modifier", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 6, name: "Collection Modifier Method Code", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 7, name: "Specimen Role", hl7Type: "CE", usage: "O", rpt: "1" },
  ],
  SRT: [
    { num: 1, name: "Sort-by Field", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Sequencing", hl7Type: "ID", table: 397, usage: "O", rpt: "1" },
  ],
  TQ: [
    { num: 1, name: "Quantity", hl7Type: "CQ", usage: "O", rpt: "1" },
    { num: 2, name: "Interval", hl7Type: "RI", usage: "O", rpt: "1" },
    { num: 3, name: "Duration", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Start Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 5, name: "End Date/time", hl7Type: "TS", usage: "O", rpt: "1" },
    { num: 6, name: "Priority", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Condition", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 8, name: "Text", hl7Type: "TX", usage: "O", rpt: "1" },
    { num: 9, name: "Conjunction", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 10, name: "Order Sequencing", hl7Type: "CM_OSD", usage: "O", rpt: "1" },
    { num: 11, name: "Occurrence Duration", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 12, name: "Total Occurences", hl7Type: "NM", usage: "O", rpt: "1" },
  ],
  TS: [
    { num: 1, name: "Time Of An Event", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Degree Of Precision", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  UVC: [
    { num: 1, name: "Value Code", hl7Type: "CWE", table: 153, usage: "R", rpt: "1" },
    { num: 2, name: "Value Amount", hl7Type: "MO", usage: "O", rpt: "1" },
    { num: 3, name: "Non-monetary Value Amount / Quantity", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 4, name: "Non-monetary Value Amount / Units", hl7Type: "CWE", usage: "O", rpt: "1" },
  ],
  VH: [
    { num: 1, name: "Start Day Range", hl7Type: "ID", table: 267, usage: "O", rpt: "1" },
    { num: 2, name: "End Day Range", hl7Type: "ID", table: 267, usage: "O", rpt: "1" },
    { num: 3, name: "Start Hour Range", hl7Type: "TM", usage: "O", rpt: "1" },
    { num: 4, name: "End Hour Range", hl7Type: "TM", usage: "O", rpt: "1" },
  ],
  VID: [
    { num: 1, name: "Version Id", hl7Type: "ID", table: 104, usage: "O", rpt: "1" },
    { num: 2, name: "Internationalization Code", hl7Type: "CE", usage: "O", rpt: "1" },
    { num: 3, name: "International Version Id", hl7Type: "CE", usage: "O", rpt: "1" },
  ],
  VR: [
    { num: 1, name: "First Data Code Value", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Last Data Code Value", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  WVI: [
    { num: 1, name: "Channel Number", hl7Type: "NM", usage: "O", rpt: "1" },
    { num: 2, name: "Channel Name", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  WVS: [
    { num: 1, name: "Source Name 1", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 2, name: "Source Name 2", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  XAD: [
    { num: 1, name: "Street Address", hl7Type: "SAD", length: { max: 184 }, usage: "O", rpt: "1" },
    { num: 2, name: "Other Designation", hl7Type: "ST", length: { max: 120 }, usage: "O", rpt: "1" },
    { num: 3, name: "City", hl7Type: "ST", length: { max: 50 }, usage: "O", rpt: "1" },
    { num: 4, name: "State Or Province", hl7Type: "ST", length: { max: 50 }, usage: "O", rpt: "1" },
    { num: 5, name: "Zip Or Postal Code", hl7Type: "ST", length: { max: 12 }, usage: "O", rpt: "1" },
    { num: 6, name: "Country", hl7Type: "ID", length: { max: 3 }, table: 399, usage: "O", rpt: "1" },
    { num: 7, name: "Address Type", hl7Type: "ID", length: { max: 3 }, table: 190, usage: "O", rpt: "1" },
    { num: 8, name: "Other Geographic Designation", hl7Type: "ST", length: { max: 50 }, usage: "O", rpt: "1" },
    { num: 9, name: "County/Parish Code", hl7Type: "IS", length: { max: 20 }, table: 289, usage: "O", rpt: "1" },
    { num: 10, name: "Census Tract", hl7Type: "IS", length: { max: 20 }, table: 288, usage: "O", rpt: "1" },
    { num: 11, name: "Address Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
    { num: 12, name: "Address Validity Range", hl7Type: "DR", length: { max: 49 }, usage: "B", rpt: "1" },
    { num: 13, name: "Effective Date", hl7Type: "DTM", length: { max: 24 }, usage: "O", rpt: "1" },
    { num: 14, name: "Expiration Date", hl7Type: "DTM", length: { max: 24 }, usage: "O", rpt: "1" },
    { num: 15, name: "Expiration Reason", hl7Type: "CWE", length: { max: 705 }, table: 616, usage: "O", rpt: "1" },
    { num: 16, name: "Temporary Indicator", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "O", rpt: "1" },
    { num: 17, name: "Bad Address Indicator", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "O", rpt: "1" },
    { num: 18, name: "Address Usage", hl7Type: "ID", length: { max: 44 }, table: 617, usage: "O", rpt: "1" },
    { num: 19, name: "Addressee", hl7Type: "ST", length: { max: 199 }, usage: "O", rpt: "1" },
    { num: 20, name: "Comment", hl7Type: "ST", length: { max: 199 }, usage: "O", rpt: "1" },
    { num: 21, name: "Preference Order", hl7Type: "NM", length: { max: 2 }, usage: "O", rpt: "1" },
    { num: 22, name: "Protection Code", hl7Type: "CWE", length: { max: 705 }, table: 618, usage: "O", rpt: "1" },
    { num: 23, name: "Address Identifier", hl7Type: "EI", length: { max: 427 }, usage: "O", rpt: "1" },
  ],
  XCN: [
    { num: 1, name: "Person Identifier", hl7Type: "ST", usage: "D", rpt: "1" },
    { num: 2, name: "Family Name", hl7Type: "FN", usage: "D", rpt: "1" },
    { num: 3, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Second And Further Given Names Or Initials Thereof", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Suffix (e.g., Jr Or Iii)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Prefix (e.g., Dr)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 7, name: "Degree (e.g., Md)", hl7Type: "ST", usage: "W", rpt: "1" },
    { num: 8, name: "Source Table", hl7Type: "CWE", table: 297, usage: "B", rpt: "1" },
    { num: 9, name: "Assigning Authority", hl7Type: "HD", table: 363, usage: "D", rpt: "1" },
    { num: 10, name: "Name Type Code", hl7Type: "ID", length: { max: 5 }, table: 200, usage: "D", rpt: "1" },
    { num: 11, name: "Identifier Check Digit", hl7Type: "ST", length: { max: 4 }, usage: "O", rpt: "1" },
    { num: 12, name: "Check Digit Scheme", hl7Type: "ID", length: { max: 3 }, table: 61, usage: "D", rpt: "1" },
    { num: 13, name: "Identifier Type Code", hl7Type: "ID", length: { max: 5 }, table: 203, usage: "D", rpt: "1" },
    { num: 14, name: "Assigning Facility", hl7Type: "HD", usage: "O", rpt: "1" },
    { num: 15, name: "Name Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
    { num: 16, name: "Name Context", hl7Type: "CWE", table: 448, usage: "O", rpt: "1" },
    { num: 17, name: "Name Validity Range", hl7Type: "ST", usage: "W", rpt: "1" },
    { num: 18, name: "Name Assembly Order", hl7Type: "ID", length: { max: 1 }, table: 444, usage: "O", rpt: "1" },
    { num: 19, name: "Effective Date", hl7Type: "DTM", usage: "O", rpt: "1" },
    { num: 20, name: "Expiration Date", hl7Type: "DTM", usage: "O", rpt: "1" },
    { num: 21, name: "Professional Suffix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 22, name: "Assigning Jurisdiction", hl7Type: "CWE", usage: "D", rpt: "1" },
    { num: 23, name: "Assigning Agency Or Department", hl7Type: "CWE", usage: "D", rpt: "1" },
    { num: 24, name: "Security Check", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 25, name: "Security Check Scheme", hl7Type: "ID", length: { max: 3 }, table: 904, usage: "O", rpt: "1" },
  ],
  XON: [
    { num: 1, name: "Organization Name", hl7Type: "ST", length: { max: 50 }, usage: "O", rpt: "1" },
    { num: 2, name: "Organization Name Type Code", hl7Type: "IS", length: { max: 20 }, table: 204, usage: "O", rpt: "1" },
    { num: 3, name: "Id Number", hl7Type: "NM", length: { max: 4 }, usage: "B", rpt: "1" },
    { num: 4, name: "Check Digit", hl7Type: "NM", length: { max: 1 }, usage: "O", rpt: "1" },
    { num: 5, name: "Check Digit Scheme", hl7Type: "ID", length: { max: 3 }, table: 61, usage: "O", rpt: "1" },
    { num: 6, name: "Assigning Authority", hl7Type: "HD", length: { max: 227 }, table: 363, usage: "O", rpt: "1" },
    { num: 7, name: "Identifier Type Code", hl7Type: "ID", length: { max: 5 }, table: 203, usage: "O", rpt: "1" },
    { num: 8, name: "Assigning Facility", hl7Type: "HD", length: { max: 227 }, usage: "O", rpt: "1" },
    { num: 9, name: "Name Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
    { num: 10, name: "Organization Identifier", hl7Type: "ST", length: { max: 20 }, usage: "O", rpt: "1" },
  ],
  XPN: [
    { num: 1, name: "Family Name", hl7Type: "FN", rpt: "1" },
    { num: 2, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 3, name: "Second And Further Given Names Or Initials Thereof", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 4, name: "Suffix (e.g., Jr Or Iii)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 5, name: "Prefix (e.g., Dr)", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 6, name: "Degree (e.g., Md)", hl7Type: "ST", usage: "W", rpt: "1" },
    { num: 7, name: "Name Type Code", hl7Type: "ID", length: { max: 5 }, table: 200, usage: "O", rpt: "1" },
    { num: 8, name: "Name Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
    { num: 9, name: "Name Context", hl7Type: "CWE", table: 448, usage: "O", rpt: "1" },
    { num: 10, name: "Name Validity Range", hl7Type: "ST", usage: "W", rpt: "1" },
    { num: 11, name: "Name Assembly Order", hl7Type: "ID", length: { max: 1 }, table: 444, usage: "O", rpt: "1" },
    { num: 12, name: "Effective Date", hl7Type: "DTM", usage: "O", rpt: "1" },
    { num: 13, name: "Expiration Date", hl7Type: "DTM", usage: "O", rpt: "1" },
    { num: 14, name: "Professional Suffix", hl7Type: "ST", usage: "O", rpt: "1" },
    { num: 15, name: "Called By", hl7Type: "ST", usage: "O", rpt: "1" },
  ],
  XTN: [
    { num: 1, name: "Telephone Number", hl7Type: "ST", usage: "W", rpt: "1" },
    { num: 2, name: "Telecommunication Use Code", hl7Type: "ID", length: { max: 3 }, table: 201, usage: "O", rpt: "1" },
    { num: 3, name: "Telecommunication Equipment Type", hl7Type: "ID", length: { max: 8 }, table: 202, usage: "O", rpt: "1" },
    { num: 4, name: "Communication Address", hl7Type: "ST", length: { max: 199 }, usage: "O", rpt: "1" },
    { num: 5, name: "Country Code", hl7Type: "NM", length: { max: 3 }, usage: "O", rpt: "1" },
    { num: 6, name: "Area/City Code", hl7Type: "NM", length: { max: 5 }, usage: "O", rpt: "1" },
    { num: 7, name: "Local Number", hl7Type: "NM", length: { max: 9 }, usage: "O", rpt: "1" },
    { num: 8, name: "Extension", hl7Type: "NM", length: { max: 5 }, usage: "O", rpt: "1" },
    { num: 9, name: "Any Text", hl7Type: "ST", length: { max: 199 }, usage: "O", rpt: "1" },
    { num: 10, name: "Extension Prefix", hl7Type: "ST", length: { max: 4 }, usage: "O", rpt: "1" },
    { num: 11, name: "Speed Dial Code", hl7Type: "ST", length: { max: 6 }, usage: "O", rpt: "1" },
    { num: 12, name: "Unformatted Telephone Number", hl7Type: "ST", length: { max: 199 }, usage: "D", rpt: "1" },
    { num: 13, name: "Effective Start Date", hl7Type: "DTM", length: { max: 24 }, usage: "O", rpt: "1" },
    { num: 14, name: "Expiration Date", hl7Type: "DTM", length: { max: 24 }, usage: "O", rpt: "1" },
    { num: 15, name: "Expiration Reason", hl7Type: "CWE", length: { max: 705 }, table: 868, usage: "O", rpt: "1" },
    { num: 16, name: "Protection Code", hl7Type: "CWE", length: { max: 705 }, table: 618, usage: "O", rpt: "1" },
    { num: 17, name: "Shared Telecommunication Identifier", hl7Type: "EI", length: { max: 427 }, usage: "O", rpt: "1" },
    { num: 18, name: "Preference Order", hl7Type: "NM", length: { max: 2 }, usage: "O", rpt: "1" },
  ],
};
