import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * DON — Donation Segment
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/DON)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const DON_SPEC: SegmentSpec = {
  description: "Donation Segment",
  fields: [
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Donation Identification Number - DIN",
      num: 1,
      usage: { "2.8": "D" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Donation Type",
      num: 2,
      usage: { "2.8": "D" },
    },
    {
      hl7Type: "DTM",
      name: "Phlebotomy Start Date/Time",
      num: 3,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "DTM",
      name: "Phlebotomy End Date/Time",
      num: 4,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "NM",
      name: "Donation Duration",
      num: 5,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Donation Duration Units",
      num: 6,
      table: 932,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Intended Procedure Type",
      num: 7,
      table: 933,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Actual Procedure Type",
      num: 8,
      table: 933,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "ID",
      name: "Donor Eligibility Flag",
      num: 9,
      table: 136,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Donor Eligibility Procedure Type",
      num: 10,
      table: 933,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "DTM",
      name: "Donor Eligibility Date",
      num: 11,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Process Interruption",
      num: 12,
      table: 923,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Process Interruption Reason",
      num: 13,
      table: 935,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Phlebotomy Issue",
      num: 14,
      table: 925,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "ID",
      name: "Intended Recipient Blood Relative",
      num: 15,
      table: 136,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "FN", name: "Family Name", num: 1, rpt: "1" },
        { hl7Type: "ST", name: "Given Name", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 3,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 6,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 7,
          rpt: "1",
          table: 200,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 8,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 9,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 10,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 11,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 12,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Called By", num: 15, rpt: "1", usage: "O" },
      ],
      hl7Type: "XPN",
      name: "Intended Recipient Name",
      num: 16,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "DTM",
      name: "Intended Recipient DOB",
      num: 17,
      usage: { "2.8": "R" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Organization Name",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Organization Name Type Code",
          num: 2,
          rpt: "1",
          table: 204,
          usage: "O",
        },
        { hl7Type: "ST", name: "Id Number", num: 3, rpt: "1", usage: "W" },
        {
          hl7Type: "ST",
          name: "Identifier Check Digit",
          num: 4,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ST",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 5,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 6,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 7,
          rpt: "1",
          table: 203,
          usage: "O",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 9,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Organization Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
      ],
      hl7Type: "XON",
      name: "Intended Recipient Facility",
      num: 18,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "DTM",
      name: "Intended Recipient Procedure Date",
      num: 19,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "FN", name: "Family Name", num: 1, rpt: "1" },
        { hl7Type: "ST", name: "Given Name", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 3,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 6,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 7,
          rpt: "1",
          table: 200,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 8,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 9,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 10,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 11,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 12,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Called By", num: 15, rpt: "1", usage: "O" },
      ],
      hl7Type: "XPN",
      name: "Intended Recipient Ordering Provider",
      num: 20,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Phlebotomy Status",
      num: 21,
      table: 926,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Arm Stick",
      num: 22,
      table: 927,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "FN", name: "Family Name", num: 1, rpt: "1" },
        { hl7Type: "ST", name: "Given Name", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 3,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 6,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 7,
          rpt: "1",
          table: 200,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 8,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 9,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 10,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 11,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 12,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Called By", num: 15, rpt: "1", usage: "O" },
      ],
      hl7Type: "XPN",
      name: "Bleed Start Phlebotomist",
      num: 23,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "FN", name: "Family Name", num: 1, rpt: "1" },
        { hl7Type: "ST", name: "Given Name", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 3,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 6,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 7,
          rpt: "1",
          table: 200,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 8,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 9,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 10,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 11,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 12,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Called By", num: 15, rpt: "1", usage: "O" },
      ],
      hl7Type: "XPN",
      name: "Bleed End Phlebotomist",
      num: 24,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "ST",
      name: "Aphaeresis Type Machine",
      num: 25,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "ST",
      name: "Aphaeresis Machine Serial Number",
      num: 26,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "ID",
      name: "Donor Reaction",
      num: 27,
      table: 136,
      usage: { "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "FN", name: "Family Name", num: 1, rpt: "1" },
        { hl7Type: "ST", name: "Given Name", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 3,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 6,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 7,
          rpt: "1",
          table: 200,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 8,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 9,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 10,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 11,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 12,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Called By", num: 15, rpt: "1", usage: "O" },
      ],
      hl7Type: "XPN",
      name: "Final Review Staff ID",
      num: 28,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "DTM",
      name: "Final Review Date/Time",
      num: 29,
      usage: { "2.8": "R" },
    },
    {
      hl7Type: "NM",
      name: "Number of Tubes Collected",
      num: 30,
      usage: { "2.8": "R" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Donation Sample Identifier",
      num: 31,
      usage: { "2.8": "R" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Person Identifier",
          num: 1,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "FN", name: "Family Name", num: 2, rpt: "1", usage: "D" },
        { hl7Type: "ST", name: "Given Name", num: 3, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 7,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "CWE",
          name: "Source Table",
          num: 8,
          rpt: "1",
          table: 297,
          usage: "B",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 9,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 10,
          rpt: "1",
          table: 200,
          usage: "D",
        },
        {
          hl7Type: "ST",
          length: { max: 4 },
          name: "Identifier Check Digit",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 12,
          rpt: "1",
          table: 61,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 13,
          rpt: "1",
          table: 203,
          usage: "D",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 15,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 16,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 17,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 18,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 19,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 20,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 22,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 23,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 24,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 25,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "XCN",
      name: "Donation Accept Staff",
      num: 32,
      usage: { "2.8": "R" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Person Identifier",
          num: 1,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "FN", name: "Family Name", num: 2, rpt: "1", usage: "D" },
        { hl7Type: "ST", name: "Given Name", num: 3, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 7,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "CWE",
          name: "Source Table",
          num: 8,
          rpt: "1",
          table: 297,
          usage: "B",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 9,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 10,
          rpt: "1",
          table: 200,
          usage: "D",
        },
        {
          hl7Type: "ST",
          length: { max: 4 },
          name: "Identifier Check Digit",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 12,
          rpt: "1",
          table: 61,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 13,
          rpt: "1",
          table: 203,
          usage: "D",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 15,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 16,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 17,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 18,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 19,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 20,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 22,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 23,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 24,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 25,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "XCN",
      name: "Donation Material Review Staff",
      num: 33,
      usage: { "2.8": "R" },
    },
  ],
  name: "DON",
  versions: ["2.8"],
};
