// Auto-generated by scripts/generate-segment-specs.mjs.
// Do not edit by hand — re-run the generator instead.
import { SegmentSpec } from "@/hl7/metadata/types";
import { ABS_SPEC } from "@/hl7/metadata/segments/abs";
import { ACC_SPEC } from "@/hl7/metadata/segments/acc";
import { ADD_SPEC } from "@/hl7/metadata/segments/add";
import { ADJ_SPEC } from "@/hl7/metadata/segments/adj";
import { AFF_SPEC } from "@/hl7/metadata/segments/aff";
import { AIG_SPEC } from "@/hl7/metadata/segments/aig";
import { AIL_SPEC } from "@/hl7/metadata/segments/ail";
import { AIP_SPEC } from "@/hl7/metadata/segments/aip";
import { AIS_SPEC } from "@/hl7/metadata/segments/ais";
import { AL1_SPEC } from "@/hl7/metadata/segments/al1";
import { APR_SPEC } from "@/hl7/metadata/segments/apr";
import { ARQ_SPEC } from "@/hl7/metadata/segments/arq";
import { ARV_SPEC } from "@/hl7/metadata/segments/arv";
import { AUT_SPEC } from "@/hl7/metadata/segments/aut";
import { BHS_SPEC } from "@/hl7/metadata/segments/bhs";
import { BLC_SPEC } from "@/hl7/metadata/segments/blc";
import { BLG_SPEC } from "@/hl7/metadata/segments/blg";
import { BPO_SPEC } from "@/hl7/metadata/segments/bpo";
import { BPX_SPEC } from "@/hl7/metadata/segments/bpx";
import { BTS_SPEC } from "@/hl7/metadata/segments/bts";
import { BTX_SPEC } from "@/hl7/metadata/segments/btx";
import { BUI_SPEC } from "@/hl7/metadata/segments/bui";
import { CDM_SPEC } from "@/hl7/metadata/segments/cdm";
import { CDO_SPEC } from "@/hl7/metadata/segments/cdo";
import { CER_SPEC } from "@/hl7/metadata/segments/cer";
import { CM0_SPEC } from "@/hl7/metadata/segments/cm0";
import { CM1_SPEC } from "@/hl7/metadata/segments/cm1";
import { CM2_SPEC } from "@/hl7/metadata/segments/cm2";
import { CNS_SPEC } from "@/hl7/metadata/segments/cns";
import { CON_SPEC } from "@/hl7/metadata/segments/con";
import { CSP_SPEC } from "@/hl7/metadata/segments/csp";
import { CSR_SPEC } from "@/hl7/metadata/segments/csr";
import { CSS_SPEC } from "@/hl7/metadata/segments/css";
import { CTD_SPEC } from "@/hl7/metadata/segments/ctd";
import { CTI_SPEC } from "@/hl7/metadata/segments/cti";
import { DB1_SPEC } from "@/hl7/metadata/segments/db1";
import { DG1_SPEC } from "@/hl7/metadata/segments/dg1";
import { DMI_SPEC } from "@/hl7/metadata/segments/dmi";
import { DON_SPEC } from "@/hl7/metadata/segments/don";
import { DRG_SPEC } from "@/hl7/metadata/segments/drg";
import { DSC_SPEC } from "@/hl7/metadata/segments/dsc";
import { DSP_SPEC } from "@/hl7/metadata/segments/dsp";
import { ECD_SPEC } from "@/hl7/metadata/segments/ecd";
import { ECR_SPEC } from "@/hl7/metadata/segments/ecr";
import { EDU_SPEC } from "@/hl7/metadata/segments/edu";
import { EQL_SPEC } from "@/hl7/metadata/segments/eql";
import { EQP_SPEC } from "@/hl7/metadata/segments/eqp";
import { EQU_SPEC } from "@/hl7/metadata/segments/equ";
import { ERQ_SPEC } from "@/hl7/metadata/segments/erq";
import { ERR_SPEC } from "@/hl7/metadata/segments/err";
import { EVN_SPEC } from "@/hl7/metadata/segments/evn";
import { FAC_SPEC } from "@/hl7/metadata/segments/fac";
import { FHS_SPEC } from "@/hl7/metadata/segments/fhs";
import { FT1_SPEC } from "@/hl7/metadata/segments/ft1";
import { FTS_SPEC } from "@/hl7/metadata/segments/fts";
import { GOL_SPEC } from "@/hl7/metadata/segments/gol";
import { GP1_SPEC } from "@/hl7/metadata/segments/gp1";
import { GP2_SPEC } from "@/hl7/metadata/segments/gp2";
import { GT1_SPEC } from "@/hl7/metadata/segments/gt1";
import { Hxx_SPEC } from "@/hl7/metadata/segments/hxx";
import { IAM_SPEC } from "@/hl7/metadata/segments/iam";
import { IAR_SPEC } from "@/hl7/metadata/segments/iar";
import { IIM_SPEC } from "@/hl7/metadata/segments/iim";
import { ILT_SPEC } from "@/hl7/metadata/segments/ilt";
import { IN1_SPEC } from "@/hl7/metadata/segments/in1";
import { IN2_SPEC } from "@/hl7/metadata/segments/in2";
import { IN3_SPEC } from "@/hl7/metadata/segments/in3";
import { INV_SPEC } from "@/hl7/metadata/segments/inv";
import { IPC_SPEC } from "@/hl7/metadata/segments/ipc";
import { IPR_SPEC } from "@/hl7/metadata/segments/ipr";
import { ISD_SPEC } from "@/hl7/metadata/segments/isd";
import { ITM_SPEC } from "@/hl7/metadata/segments/itm";
import { IVC_SPEC } from "@/hl7/metadata/segments/ivc";
import { IVT_SPEC } from "@/hl7/metadata/segments/ivt";
import { LAN_SPEC } from "@/hl7/metadata/segments/lan";
import { LCC_SPEC } from "@/hl7/metadata/segments/lcc";
import { LCH_SPEC } from "@/hl7/metadata/segments/lch";
import { LDP_SPEC } from "@/hl7/metadata/segments/ldp";
import { LOC_SPEC } from "@/hl7/metadata/segments/loc";
import { LRL_SPEC } from "@/hl7/metadata/segments/lrl";
import { MFA_SPEC } from "@/hl7/metadata/segments/mfa";
import { MFE_SPEC } from "@/hl7/metadata/segments/mfe";
import { MFI_SPEC } from "@/hl7/metadata/segments/mfi";
import { MRG_SPEC } from "@/hl7/metadata/segments/mrg";
import { MSA_SPEC } from "@/hl7/metadata/segments/msa";
import { MSH_SPEC } from "@/hl7/metadata/segments/msh";
import { NCK_SPEC } from "@/hl7/metadata/segments/nck";
import { NDS_SPEC } from "@/hl7/metadata/segments/nds";
import { NK1_SPEC } from "@/hl7/metadata/segments/nk1";
import { NPU_SPEC } from "@/hl7/metadata/segments/npu";
import { NSC_SPEC } from "@/hl7/metadata/segments/nsc";
import { NST_SPEC } from "@/hl7/metadata/segments/nst";
import { NTE_SPEC } from "@/hl7/metadata/segments/nte";
import { OBR_SPEC } from "@/hl7/metadata/segments/obr";
import { OBX_SPEC } from "@/hl7/metadata/segments/obx";
import { ODS_SPEC } from "@/hl7/metadata/segments/ods";
import { ODT_SPEC } from "@/hl7/metadata/segments/odt";
import { OM1_SPEC } from "@/hl7/metadata/segments/om1";
import { OM2_SPEC } from "@/hl7/metadata/segments/om2";
import { OM3_SPEC } from "@/hl7/metadata/segments/om3";
import { OM4_SPEC } from "@/hl7/metadata/segments/om4";
import { OM5_SPEC } from "@/hl7/metadata/segments/om5";
import { OM6_SPEC } from "@/hl7/metadata/segments/om6";
import { OM7_SPEC } from "@/hl7/metadata/segments/om7";
import { ORC_SPEC } from "@/hl7/metadata/segments/orc";
import { ORG_SPEC } from "@/hl7/metadata/segments/org";
import { ORO_SPEC } from "@/hl7/metadata/segments/oro";
import { OVR_SPEC } from "@/hl7/metadata/segments/ovr";
import { PAC_SPEC } from "@/hl7/metadata/segments/pac";
import { PCE_SPEC } from "@/hl7/metadata/segments/pce";
import { PCR_SPEC } from "@/hl7/metadata/segments/pcr";
import { PD1_SPEC } from "@/hl7/metadata/segments/pd1";
import { PDA_SPEC } from "@/hl7/metadata/segments/pda";
import { PDC_SPEC } from "@/hl7/metadata/segments/pdc";
import { PEO_SPEC } from "@/hl7/metadata/segments/peo";
import { PES_SPEC } from "@/hl7/metadata/segments/pes";
import { PID_SPEC } from "@/hl7/metadata/segments/pid";
import { PKG_SPEC } from "@/hl7/metadata/segments/pkg";
import { PMT_SPEC } from "@/hl7/metadata/segments/pmt";
import { PR1_SPEC } from "@/hl7/metadata/segments/pr1";
import { PRA_SPEC } from "@/hl7/metadata/segments/pra";
import { PRB_SPEC } from "@/hl7/metadata/segments/prb";
import { PRC_SPEC } from "@/hl7/metadata/segments/prc";
import { PRD_SPEC } from "@/hl7/metadata/segments/prd";
import { PRT_SPEC } from "@/hl7/metadata/segments/prt";
import { PSG_SPEC } from "@/hl7/metadata/segments/psg";
import { PSH_SPEC } from "@/hl7/metadata/segments/psh";
import { PSL_SPEC } from "@/hl7/metadata/segments/psl";
import { PSS_SPEC } from "@/hl7/metadata/segments/pss";
import { PTH_SPEC } from "@/hl7/metadata/segments/pth";
import { PV1_SPEC } from "@/hl7/metadata/segments/pv1";
import { PV2_SPEC } from "@/hl7/metadata/segments/pv2";
import { PYE_SPEC } from "@/hl7/metadata/segments/pye";
import { QAK_SPEC } from "@/hl7/metadata/segments/qak";
import { QID_SPEC } from "@/hl7/metadata/segments/qid";
import { QPD_SPEC } from "@/hl7/metadata/segments/qpd";
import { QRD_SPEC } from "@/hl7/metadata/segments/qrd";
import { QRF_SPEC } from "@/hl7/metadata/segments/qrf";
import { QRI_SPEC } from "@/hl7/metadata/segments/qri";
import { RCP_SPEC } from "@/hl7/metadata/segments/rcp";
import { RDF_SPEC } from "@/hl7/metadata/segments/rdf";
import { RDT_SPEC } from "@/hl7/metadata/segments/rdt";
import { REL_SPEC } from "@/hl7/metadata/segments/rel";
import { RF1_SPEC } from "@/hl7/metadata/segments/rf1";
import { RFI_SPEC } from "@/hl7/metadata/segments/rfi";
import { RGS_SPEC } from "@/hl7/metadata/segments/rgs";
import { RMI_SPEC } from "@/hl7/metadata/segments/rmi";
import { ROL_SPEC } from "@/hl7/metadata/segments/rol";
import { RQ1_SPEC } from "@/hl7/metadata/segments/rq1";
import { RQD_SPEC } from "@/hl7/metadata/segments/rqd";
import { RX1_SPEC } from "@/hl7/metadata/segments/rx1";
import { RXA_SPEC } from "@/hl7/metadata/segments/rxa";
import { RXC_SPEC } from "@/hl7/metadata/segments/rxc";
import { RXD_SPEC } from "@/hl7/metadata/segments/rxd";
import { RXE_SPEC } from "@/hl7/metadata/segments/rxe";
import { RXG_SPEC } from "@/hl7/metadata/segments/rxg";
import { RXO_SPEC } from "@/hl7/metadata/segments/rxo";
import { RXR_SPEC } from "@/hl7/metadata/segments/rxr";
import { RXV_SPEC } from "@/hl7/metadata/segments/rxv";
import { SAC_SPEC } from "@/hl7/metadata/segments/sac";
import { SCD_SPEC } from "@/hl7/metadata/segments/scd";
import { SCH_SPEC } from "@/hl7/metadata/segments/sch";
import { SCP_SPEC } from "@/hl7/metadata/segments/scp";
import { SDD_SPEC } from "@/hl7/metadata/segments/sdd";
import { SFT_SPEC } from "@/hl7/metadata/segments/sft";
import { SHP_SPEC } from "@/hl7/metadata/segments/shp";
import { SID_SPEC } from "@/hl7/metadata/segments/sid";
import { SLT_SPEC } from "@/hl7/metadata/segments/slt";
import { SPM_SPEC } from "@/hl7/metadata/segments/spm";
import { SPR_SPEC } from "@/hl7/metadata/segments/spr";
import { STF_SPEC } from "@/hl7/metadata/segments/stf";
import { STZ_SPEC } from "@/hl7/metadata/segments/stz";
import { TCC_SPEC } from "@/hl7/metadata/segments/tcc";
import { TCD_SPEC } from "@/hl7/metadata/segments/tcd";
import { TQ1_SPEC } from "@/hl7/metadata/segments/tq1";
import { TQ2_SPEC } from "@/hl7/metadata/segments/tq2";
import { TXA_SPEC } from "@/hl7/metadata/segments/txa";
import { UAC_SPEC } from "@/hl7/metadata/segments/uac";
import { UB1_SPEC } from "@/hl7/metadata/segments/ub1";
import { UB2_SPEC } from "@/hl7/metadata/segments/ub2";
import { URD_SPEC } from "@/hl7/metadata/segments/urd";
import { URS_SPEC } from "@/hl7/metadata/segments/urs";
import { VAR_SPEC } from "@/hl7/metadata/segments/var";
import { VND_SPEC } from "@/hl7/metadata/segments/vnd";
import { VTQ_SPEC } from "@/hl7/metadata/segments/vtq";
import { ZL7_SPEC } from "@/hl7/metadata/segments/zl7";
import { Zxx_SPEC } from "@/hl7/metadata/segments/zxx";

export { ABS_SPEC } from "@/hl7/metadata/segments/abs";
export { ACC_SPEC } from "@/hl7/metadata/segments/acc";
export { ADD_SPEC } from "@/hl7/metadata/segments/add";
export { ADJ_SPEC } from "@/hl7/metadata/segments/adj";
export { AFF_SPEC } from "@/hl7/metadata/segments/aff";
export { AIG_SPEC } from "@/hl7/metadata/segments/aig";
export { AIL_SPEC } from "@/hl7/metadata/segments/ail";
export { AIP_SPEC } from "@/hl7/metadata/segments/aip";
export { AIS_SPEC } from "@/hl7/metadata/segments/ais";
export { AL1_SPEC } from "@/hl7/metadata/segments/al1";
export { APR_SPEC } from "@/hl7/metadata/segments/apr";
export { ARQ_SPEC } from "@/hl7/metadata/segments/arq";
export { ARV_SPEC } from "@/hl7/metadata/segments/arv";
export { AUT_SPEC } from "@/hl7/metadata/segments/aut";
export { BHS_SPEC } from "@/hl7/metadata/segments/bhs";
export { BLC_SPEC } from "@/hl7/metadata/segments/blc";
export { BLG_SPEC } from "@/hl7/metadata/segments/blg";
export { BPO_SPEC } from "@/hl7/metadata/segments/bpo";
export { BPX_SPEC } from "@/hl7/metadata/segments/bpx";
export { BTS_SPEC } from "@/hl7/metadata/segments/bts";
export { BTX_SPEC } from "@/hl7/metadata/segments/btx";
export { BUI_SPEC } from "@/hl7/metadata/segments/bui";
export { CDM_SPEC } from "@/hl7/metadata/segments/cdm";
export { CDO_SPEC } from "@/hl7/metadata/segments/cdo";
export { CER_SPEC } from "@/hl7/metadata/segments/cer";
export { CM0_SPEC } from "@/hl7/metadata/segments/cm0";
export { CM1_SPEC } from "@/hl7/metadata/segments/cm1";
export { CM2_SPEC } from "@/hl7/metadata/segments/cm2";
export { CNS_SPEC } from "@/hl7/metadata/segments/cns";
export { CON_SPEC } from "@/hl7/metadata/segments/con";
export { CSP_SPEC } from "@/hl7/metadata/segments/csp";
export { CSR_SPEC } from "@/hl7/metadata/segments/csr";
export { CSS_SPEC } from "@/hl7/metadata/segments/css";
export { CTD_SPEC } from "@/hl7/metadata/segments/ctd";
export { CTI_SPEC } from "@/hl7/metadata/segments/cti";
export { DB1_SPEC } from "@/hl7/metadata/segments/db1";
export { DG1_SPEC } from "@/hl7/metadata/segments/dg1";
export { DMI_SPEC } from "@/hl7/metadata/segments/dmi";
export { DON_SPEC } from "@/hl7/metadata/segments/don";
export { DRG_SPEC } from "@/hl7/metadata/segments/drg";
export { DSC_SPEC } from "@/hl7/metadata/segments/dsc";
export { DSP_SPEC } from "@/hl7/metadata/segments/dsp";
export { ECD_SPEC } from "@/hl7/metadata/segments/ecd";
export { ECR_SPEC } from "@/hl7/metadata/segments/ecr";
export { EDU_SPEC } from "@/hl7/metadata/segments/edu";
export { EQL_SPEC } from "@/hl7/metadata/segments/eql";
export { EQP_SPEC } from "@/hl7/metadata/segments/eqp";
export { EQU_SPEC } from "@/hl7/metadata/segments/equ";
export { ERQ_SPEC } from "@/hl7/metadata/segments/erq";
export { ERR_SPEC } from "@/hl7/metadata/segments/err";
export { EVN_SPEC } from "@/hl7/metadata/segments/evn";
export { FAC_SPEC } from "@/hl7/metadata/segments/fac";
export { FHS_SPEC } from "@/hl7/metadata/segments/fhs";
export { FT1_SPEC } from "@/hl7/metadata/segments/ft1";
export { FTS_SPEC } from "@/hl7/metadata/segments/fts";
export { GOL_SPEC } from "@/hl7/metadata/segments/gol";
export { GP1_SPEC } from "@/hl7/metadata/segments/gp1";
export { GP2_SPEC } from "@/hl7/metadata/segments/gp2";
export { GT1_SPEC } from "@/hl7/metadata/segments/gt1";
export { Hxx_SPEC } from "@/hl7/metadata/segments/hxx";
export { IAM_SPEC } from "@/hl7/metadata/segments/iam";
export { IAR_SPEC } from "@/hl7/metadata/segments/iar";
export { IIM_SPEC } from "@/hl7/metadata/segments/iim";
export { ILT_SPEC } from "@/hl7/metadata/segments/ilt";
export { IN1_SPEC } from "@/hl7/metadata/segments/in1";
export { IN2_SPEC } from "@/hl7/metadata/segments/in2";
export { IN3_SPEC } from "@/hl7/metadata/segments/in3";
export { INV_SPEC } from "@/hl7/metadata/segments/inv";
export { IPC_SPEC } from "@/hl7/metadata/segments/ipc";
export { IPR_SPEC } from "@/hl7/metadata/segments/ipr";
export { ISD_SPEC } from "@/hl7/metadata/segments/isd";
export { ITM_SPEC } from "@/hl7/metadata/segments/itm";
export { IVC_SPEC } from "@/hl7/metadata/segments/ivc";
export { IVT_SPEC } from "@/hl7/metadata/segments/ivt";
export { LAN_SPEC } from "@/hl7/metadata/segments/lan";
export { LCC_SPEC } from "@/hl7/metadata/segments/lcc";
export { LCH_SPEC } from "@/hl7/metadata/segments/lch";
export { LDP_SPEC } from "@/hl7/metadata/segments/ldp";
export { LOC_SPEC } from "@/hl7/metadata/segments/loc";
export { LRL_SPEC } from "@/hl7/metadata/segments/lrl";
export { MFA_SPEC } from "@/hl7/metadata/segments/mfa";
export { MFE_SPEC } from "@/hl7/metadata/segments/mfe";
export { MFI_SPEC } from "@/hl7/metadata/segments/mfi";
export { MRG_SPEC } from "@/hl7/metadata/segments/mrg";
export { MSA_SPEC } from "@/hl7/metadata/segments/msa";
export { MSH_SPEC } from "@/hl7/metadata/segments/msh";
export { NCK_SPEC } from "@/hl7/metadata/segments/nck";
export { NDS_SPEC } from "@/hl7/metadata/segments/nds";
export { NK1_SPEC } from "@/hl7/metadata/segments/nk1";
export { NPU_SPEC } from "@/hl7/metadata/segments/npu";
export { NSC_SPEC } from "@/hl7/metadata/segments/nsc";
export { NST_SPEC } from "@/hl7/metadata/segments/nst";
export { NTE_SPEC } from "@/hl7/metadata/segments/nte";
export { OBR_SPEC } from "@/hl7/metadata/segments/obr";
export { OBX_SPEC } from "@/hl7/metadata/segments/obx";
export { ODS_SPEC } from "@/hl7/metadata/segments/ods";
export { ODT_SPEC } from "@/hl7/metadata/segments/odt";
export { OM1_SPEC } from "@/hl7/metadata/segments/om1";
export { OM2_SPEC } from "@/hl7/metadata/segments/om2";
export { OM3_SPEC } from "@/hl7/metadata/segments/om3";
export { OM4_SPEC } from "@/hl7/metadata/segments/om4";
export { OM5_SPEC } from "@/hl7/metadata/segments/om5";
export { OM6_SPEC } from "@/hl7/metadata/segments/om6";
export { OM7_SPEC } from "@/hl7/metadata/segments/om7";
export { ORC_SPEC } from "@/hl7/metadata/segments/orc";
export { ORG_SPEC } from "@/hl7/metadata/segments/org";
export { ORO_SPEC } from "@/hl7/metadata/segments/oro";
export { OVR_SPEC } from "@/hl7/metadata/segments/ovr";
export { PAC_SPEC } from "@/hl7/metadata/segments/pac";
export { PCE_SPEC } from "@/hl7/metadata/segments/pce";
export { PCR_SPEC } from "@/hl7/metadata/segments/pcr";
export { PD1_SPEC } from "@/hl7/metadata/segments/pd1";
export { PDA_SPEC } from "@/hl7/metadata/segments/pda";
export { PDC_SPEC } from "@/hl7/metadata/segments/pdc";
export { PEO_SPEC } from "@/hl7/metadata/segments/peo";
export { PES_SPEC } from "@/hl7/metadata/segments/pes";
export { PID_SPEC } from "@/hl7/metadata/segments/pid";
export { PKG_SPEC } from "@/hl7/metadata/segments/pkg";
export { PMT_SPEC } from "@/hl7/metadata/segments/pmt";
export { PR1_SPEC } from "@/hl7/metadata/segments/pr1";
export { PRA_SPEC } from "@/hl7/metadata/segments/pra";
export { PRB_SPEC } from "@/hl7/metadata/segments/prb";
export { PRC_SPEC } from "@/hl7/metadata/segments/prc";
export { PRD_SPEC } from "@/hl7/metadata/segments/prd";
export { PRT_SPEC } from "@/hl7/metadata/segments/prt";
export { PSG_SPEC } from "@/hl7/metadata/segments/psg";
export { PSH_SPEC } from "@/hl7/metadata/segments/psh";
export { PSL_SPEC } from "@/hl7/metadata/segments/psl";
export { PSS_SPEC } from "@/hl7/metadata/segments/pss";
export { PTH_SPEC } from "@/hl7/metadata/segments/pth";
export { PV1_SPEC } from "@/hl7/metadata/segments/pv1";
export { PV2_SPEC } from "@/hl7/metadata/segments/pv2";
export { PYE_SPEC } from "@/hl7/metadata/segments/pye";
export { QAK_SPEC } from "@/hl7/metadata/segments/qak";
export { QID_SPEC } from "@/hl7/metadata/segments/qid";
export { QPD_SPEC } from "@/hl7/metadata/segments/qpd";
export { QRD_SPEC } from "@/hl7/metadata/segments/qrd";
export { QRF_SPEC } from "@/hl7/metadata/segments/qrf";
export { QRI_SPEC } from "@/hl7/metadata/segments/qri";
export { RCP_SPEC } from "@/hl7/metadata/segments/rcp";
export { RDF_SPEC } from "@/hl7/metadata/segments/rdf";
export { RDT_SPEC } from "@/hl7/metadata/segments/rdt";
export { REL_SPEC } from "@/hl7/metadata/segments/rel";
export { RF1_SPEC } from "@/hl7/metadata/segments/rf1";
export { RFI_SPEC } from "@/hl7/metadata/segments/rfi";
export { RGS_SPEC } from "@/hl7/metadata/segments/rgs";
export { RMI_SPEC } from "@/hl7/metadata/segments/rmi";
export { ROL_SPEC } from "@/hl7/metadata/segments/rol";
export { RQ1_SPEC } from "@/hl7/metadata/segments/rq1";
export { RQD_SPEC } from "@/hl7/metadata/segments/rqd";
export { RX1_SPEC } from "@/hl7/metadata/segments/rx1";
export { RXA_SPEC } from "@/hl7/metadata/segments/rxa";
export { RXC_SPEC } from "@/hl7/metadata/segments/rxc";
export { RXD_SPEC } from "@/hl7/metadata/segments/rxd";
export { RXE_SPEC } from "@/hl7/metadata/segments/rxe";
export { RXG_SPEC } from "@/hl7/metadata/segments/rxg";
export { RXO_SPEC } from "@/hl7/metadata/segments/rxo";
export { RXR_SPEC } from "@/hl7/metadata/segments/rxr";
export { RXV_SPEC } from "@/hl7/metadata/segments/rxv";
export { SAC_SPEC } from "@/hl7/metadata/segments/sac";
export { SCD_SPEC } from "@/hl7/metadata/segments/scd";
export { SCH_SPEC } from "@/hl7/metadata/segments/sch";
export { SCP_SPEC } from "@/hl7/metadata/segments/scp";
export { SDD_SPEC } from "@/hl7/metadata/segments/sdd";
export { SFT_SPEC } from "@/hl7/metadata/segments/sft";
export { SHP_SPEC } from "@/hl7/metadata/segments/shp";
export { SID_SPEC } from "@/hl7/metadata/segments/sid";
export { SLT_SPEC } from "@/hl7/metadata/segments/slt";
export { SPM_SPEC } from "@/hl7/metadata/segments/spm";
export { SPR_SPEC } from "@/hl7/metadata/segments/spr";
export { STF_SPEC } from "@/hl7/metadata/segments/stf";
export { STZ_SPEC } from "@/hl7/metadata/segments/stz";
export { TCC_SPEC } from "@/hl7/metadata/segments/tcc";
export { TCD_SPEC } from "@/hl7/metadata/segments/tcd";
export { TQ1_SPEC } from "@/hl7/metadata/segments/tq1";
export { TQ2_SPEC } from "@/hl7/metadata/segments/tq2";
export { TXA_SPEC } from "@/hl7/metadata/segments/txa";
export { UAC_SPEC } from "@/hl7/metadata/segments/uac";
export { UB1_SPEC } from "@/hl7/metadata/segments/ub1";
export { UB2_SPEC } from "@/hl7/metadata/segments/ub2";
export { URD_SPEC } from "@/hl7/metadata/segments/urd";
export { URS_SPEC } from "@/hl7/metadata/segments/urs";
export { VAR_SPEC } from "@/hl7/metadata/segments/var";
export { VND_SPEC } from "@/hl7/metadata/segments/vnd";
export { VTQ_SPEC } from "@/hl7/metadata/segments/vtq";
export { ZL7_SPEC } from "@/hl7/metadata/segments/zl7";
export { Zxx_SPEC } from "@/hl7/metadata/segments/zxx";

/**
 * Lookup of every generated SegmentSpec, keyed by uppercase segment name.
 *
 * @since RELEASE_VERSION_PLACEHOLDER 
 */
export const SEGMENT_SPECS: Readonly<Record<string, SegmentSpec>> = {
  ABS: ABS_SPEC,
  ACC: ACC_SPEC,
  ADD: ADD_SPEC,
  ADJ: ADJ_SPEC,
  AFF: AFF_SPEC,
  AIG: AIG_SPEC,
  AIL: AIL_SPEC,
  AIP: AIP_SPEC,
  AIS: AIS_SPEC,
  AL1: AL1_SPEC,
  APR: APR_SPEC,
  ARQ: ARQ_SPEC,
  ARV: ARV_SPEC,
  AUT: AUT_SPEC,
  BHS: BHS_SPEC,
  BLC: BLC_SPEC,
  BLG: BLG_SPEC,
  BPO: BPO_SPEC,
  BPX: BPX_SPEC,
  BTS: BTS_SPEC,
  BTX: BTX_SPEC,
  BUI: BUI_SPEC,
  CDM: CDM_SPEC,
  CDO: CDO_SPEC,
  CER: CER_SPEC,
  CM0: CM0_SPEC,
  CM1: CM1_SPEC,
  CM2: CM2_SPEC,
  CNS: CNS_SPEC,
  CON: CON_SPEC,
  CSP: CSP_SPEC,
  CSR: CSR_SPEC,
  CSS: CSS_SPEC,
  CTD: CTD_SPEC,
  CTI: CTI_SPEC,
  DB1: DB1_SPEC,
  DG1: DG1_SPEC,
  DMI: DMI_SPEC,
  DON: DON_SPEC,
  DRG: DRG_SPEC,
  DSC: DSC_SPEC,
  DSP: DSP_SPEC,
  ECD: ECD_SPEC,
  ECR: ECR_SPEC,
  EDU: EDU_SPEC,
  EQL: EQL_SPEC,
  EQP: EQP_SPEC,
  EQU: EQU_SPEC,
  ERQ: ERQ_SPEC,
  ERR: ERR_SPEC,
  EVN: EVN_SPEC,
  FAC: FAC_SPEC,
  FHS: FHS_SPEC,
  FT1: FT1_SPEC,
  FTS: FTS_SPEC,
  GOL: GOL_SPEC,
  GP1: GP1_SPEC,
  GP2: GP2_SPEC,
  GT1: GT1_SPEC,
  Hxx: Hxx_SPEC,
  IAM: IAM_SPEC,
  IAR: IAR_SPEC,
  IIM: IIM_SPEC,
  ILT: ILT_SPEC,
  IN1: IN1_SPEC,
  IN2: IN2_SPEC,
  IN3: IN3_SPEC,
  INV: INV_SPEC,
  IPC: IPC_SPEC,
  IPR: IPR_SPEC,
  ISD: ISD_SPEC,
  ITM: ITM_SPEC,
  IVC: IVC_SPEC,
  IVT: IVT_SPEC,
  LAN: LAN_SPEC,
  LCC: LCC_SPEC,
  LCH: LCH_SPEC,
  LDP: LDP_SPEC,
  LOC: LOC_SPEC,
  LRL: LRL_SPEC,
  MFA: MFA_SPEC,
  MFE: MFE_SPEC,
  MFI: MFI_SPEC,
  MRG: MRG_SPEC,
  MSA: MSA_SPEC,
  MSH: MSH_SPEC,
  NCK: NCK_SPEC,
  NDS: NDS_SPEC,
  NK1: NK1_SPEC,
  NPU: NPU_SPEC,
  NSC: NSC_SPEC,
  NST: NST_SPEC,
  NTE: NTE_SPEC,
  OBR: OBR_SPEC,
  OBX: OBX_SPEC,
  ODS: ODS_SPEC,
  ODT: ODT_SPEC,
  OM1: OM1_SPEC,
  OM2: OM2_SPEC,
  OM3: OM3_SPEC,
  OM4: OM4_SPEC,
  OM5: OM5_SPEC,
  OM6: OM6_SPEC,
  OM7: OM7_SPEC,
  ORC: ORC_SPEC,
  ORG: ORG_SPEC,
  ORO: ORO_SPEC,
  OVR: OVR_SPEC,
  PAC: PAC_SPEC,
  PCE: PCE_SPEC,
  PCR: PCR_SPEC,
  PD1: PD1_SPEC,
  PDA: PDA_SPEC,
  PDC: PDC_SPEC,
  PEO: PEO_SPEC,
  PES: PES_SPEC,
  PID: PID_SPEC,
  PKG: PKG_SPEC,
  PMT: PMT_SPEC,
  PR1: PR1_SPEC,
  PRA: PRA_SPEC,
  PRB: PRB_SPEC,
  PRC: PRC_SPEC,
  PRD: PRD_SPEC,
  PRT: PRT_SPEC,
  PSG: PSG_SPEC,
  PSH: PSH_SPEC,
  PSL: PSL_SPEC,
  PSS: PSS_SPEC,
  PTH: PTH_SPEC,
  PV1: PV1_SPEC,
  PV2: PV2_SPEC,
  PYE: PYE_SPEC,
  QAK: QAK_SPEC,
  QID: QID_SPEC,
  QPD: QPD_SPEC,
  QRD: QRD_SPEC,
  QRF: QRF_SPEC,
  QRI: QRI_SPEC,
  RCP: RCP_SPEC,
  RDF: RDF_SPEC,
  RDT: RDT_SPEC,
  REL: REL_SPEC,
  RF1: RF1_SPEC,
  RFI: RFI_SPEC,
  RGS: RGS_SPEC,
  RMI: RMI_SPEC,
  ROL: ROL_SPEC,
  RQ1: RQ1_SPEC,
  RQD: RQD_SPEC,
  RX1: RX1_SPEC,
  RXA: RXA_SPEC,
  RXC: RXC_SPEC,
  RXD: RXD_SPEC,
  RXE: RXE_SPEC,
  RXG: RXG_SPEC,
  RXO: RXO_SPEC,
  RXR: RXR_SPEC,
  RXV: RXV_SPEC,
  SAC: SAC_SPEC,
  SCD: SCD_SPEC,
  SCH: SCH_SPEC,
  SCP: SCP_SPEC,
  SDD: SDD_SPEC,
  SFT: SFT_SPEC,
  SHP: SHP_SPEC,
  SID: SID_SPEC,
  SLT: SLT_SPEC,
  SPM: SPM_SPEC,
  SPR: SPR_SPEC,
  STF: STF_SPEC,
  STZ: STZ_SPEC,
  TCC: TCC_SPEC,
  TCD: TCD_SPEC,
  TQ1: TQ1_SPEC,
  TQ2: TQ2_SPEC,
  TXA: TXA_SPEC,
  UAC: UAC_SPEC,
  UB1: UB1_SPEC,
  UB2: UB2_SPEC,
  URD: URD_SPEC,
  URS: URS_SPEC,
  VAR: VAR_SPEC,
  VND: VND_SPEC,
  VTQ: VTQ_SPEC,
  ZL7: ZL7_SPEC,
  Zxx: Zxx_SPEC,
};
