import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * IVT — Material Location
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/IVT)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const IVT_SPEC: SegmentSpec = {
  description: "Material Location",
  fields: [
    {
      hl7Type: "SI",
      length: { max: 4 },
      name: "Set Id - Ivt",
      num: 1,
      usage: { "2.6": "R", "2.7": "R", "2.7.1": "R", "2.8": "R" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Inventory Location Identifier",
      num: 2,
      usage: { "2.6": "R", "2.7": "R", "2.7.1": "R", "2.8": "R" },
    },
    {
      hl7Type: "ST",
      name: "Inventory Location Name",
      num: 3,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Source Location Identifier",
      num: 4,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      hl7Type: "ST",
      name: "Source Location Name",
      num: 5,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Item Status",
      num: 6,
      table: 625,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Bin Location Identifier",
      num: 7,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Order Packaging",
      num: 8,
      table: 818,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Issue Packaging",
      num: 9,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Default Inventory Asset Account",
      num: 10,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Patient Chargeable Indicator",
      num: 11,
      table: 532,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Transaction Code",
      num: 12,
      table: 132,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "MO", name: "Price", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ID",
          length: { max: 2 },
          name: "Price Type",
          num: 2,
          rpt: "1",
          table: 205,
          usage: "O",
        },
        { hl7Type: "NM", name: "From Value", num: 3, rpt: "1", usage: "O" },
        { hl7Type: "NM", name: "To Value", num: 4, rpt: "1", usage: "O" },
        { hl7Type: "CWE", name: "Range Units", num: 5, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Range Type",
          num: 6,
          rpt: "1",
          table: 298,
          usage: "O",
        },
      ],
      hl7Type: "CP",
      name: "Transaction Amount - Unit",
      num: 13,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Item Importance Code",
      num: 14,
      table: 634,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Stocked Item Indicator",
      num: 15,
      table: 532,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Consignment Item Indicator",
      num: 16,
      table: 532,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Reusable Item Indicator",
      num: 17,
      table: 532,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "MO", name: "Price", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ID",
          length: { max: 2 },
          name: "Price Type",
          num: 2,
          rpt: "1",
          table: 205,
          usage: "O",
        },
        { hl7Type: "NM", name: "From Value", num: 3, rpt: "1", usage: "O" },
        { hl7Type: "NM", name: "To Value", num: 4, rpt: "1", usage: "O" },
        { hl7Type: "CWE", name: "Range Units", num: 5, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Range Type",
          num: 6,
          rpt: "1",
          table: 298,
          usage: "O",
        },
      ],
      hl7Type: "CP",
      name: "Reusable Cost",
      num: 18,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Substitute Item Identifier",
      num: 19,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Latex-free Substitute Item Identifier",
      num: 20,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Recommended Reorder Theory",
      num: 21,
      table: 642,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      hl7Type: "NM",
      name: "Recommended Safety Stock Days",
      num: 22,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      hl7Type: "NM",
      name: "Recommended Maximum Days Inventory",
      num: 23,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      hl7Type: "NM",
      name: "Recommended Order Point",
      num: 24,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      hl7Type: "NM",
      name: "Recommended Order Amount",
      num: 25,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "R" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CNE",
      name: "Operating Room Par Level Indicator",
      num: 26,
      table: 532,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
  ],
  name: "IVT",
  versions: ["2.6", "2.7", "2.7.1", "2.8"],
};
