/*
MIT License

Copyright (c) 2026 Shane

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * MRG — Merge Patient Information
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/MRG)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const MRG_SPEC: SegmentSpec = {
  description: "Merge Patient Information",
  fields: [
    {
      components: [
        { hl7Type: "ST", name: "Id Number", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ST",
          name: "Identifier Check Digit",
          num: 2,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 3,
          rpt: "1",
          table: 61,
          usage: "O",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 4,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 5,
          rpt: "1",
          table: 203,
          usage: "R",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "DT", name: "Effective Date", num: 7, rpt: "1", usage: "O" },
        {
          hl7Type: "DT",
          name: "Expiration Date",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 9,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 10,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 12,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "CX",
      name: "Prior Patient Identifier List",
      num: 1,
      usage: {
        "2.1": "R",
        "2.2": "R",
        "2.3": "R",
        "2.3.1": "R",
        "2.4": "R",
        "2.5": "R",
        "2.5.1": "R",
        "2.6": "R",
        "2.7": "R",
        "2.7.1": "R",
        "2.8": "R",
      },
    },
    {
      hl7Type: "ST",
      name: "Prior Alternate Patient Id",
      num: 2,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "B",
        "2.5": "B",
        "2.5.1": "B",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Id Number", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ST",
          name: "Identifier Check Digit",
          num: 2,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 3,
          rpt: "1",
          table: 61,
          usage: "O",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 4,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 5,
          rpt: "1",
          table: 203,
          usage: "R",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "DT", name: "Effective Date", num: 7, rpt: "1", usage: "O" },
        {
          hl7Type: "DT",
          name: "Expiration Date",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 9,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 10,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 12,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "CX",
      name: "Prior Patient Account Number",
      num: 3,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      hl7Type: "ST",
      name: "Prior Patient Id",
      num: 4,
      usage: {
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "B",
        "2.5": "B",
        "2.5.1": "B",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Id Number", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ST",
          name: "Identifier Check Digit",
          num: 2,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 3,
          rpt: "1",
          table: 61,
          usage: "O",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 4,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 5,
          rpt: "1",
          table: 203,
          usage: "R",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "DT", name: "Effective Date", num: 7, rpt: "1", usage: "O" },
        {
          hl7Type: "DT",
          name: "Expiration Date",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 9,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 10,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 12,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "CX",
      name: "Prior Visit Number",
      num: 5,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Id Number", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ST",
          name: "Identifier Check Digit",
          num: 2,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 3,
          rpt: "1",
          table: 61,
          usage: "O",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 4,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 5,
          rpt: "1",
          table: 203,
          usage: "R",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "DT", name: "Effective Date", num: 7, rpt: "1", usage: "O" },
        {
          hl7Type: "DT",
          name: "Expiration Date",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 9,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 10,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 12,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "CX",
      name: "Prior Alternate Visit Id",
      num: 6,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "FN", name: "Family Name", num: 1, rpt: "1" },
        { hl7Type: "ST", name: "Given Name", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 3,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 6,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 7,
          rpt: "1",
          table: 200,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 8,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 9,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 10,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 11,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 12,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Called By", num: 15, rpt: "1", usage: "O" },
      ],
      hl7Type: "XPN",
      name: "Prior Patient Name",
      num: 7,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
  ],
  name: "MRG",
  versions: [
    "2.1",
    "2.2",
    "2.3",
    "2.3.1",
    "2.4",
    "2.5",
    "2.5.1",
    "2.6",
    "2.7",
    "2.7.1",
    "2.8",
  ],
};
