/*
MIT License

Copyright (c) 2026 Shane

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * OVR — Override Segment
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/OVR)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const OVR_SPEC: SegmentSpec = {
  description: "Override Segment",
  fields: [
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Business Rule Override Type",
      num: 1,
      table: 518,
      usage: {
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Business Rule Override Code",
      num: 2,
      table: 521,
      usage: {
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      hl7Type: "TX",
      name: "Override Comments",
      num: 3,
      usage: {
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Person Identifier",
          num: 1,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "FN", name: "Family Name", num: 2, rpt: "1", usage: "D" },
        { hl7Type: "ST", name: "Given Name", num: 3, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 7,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "CWE",
          name: "Source Table",
          num: 8,
          rpt: "1",
          table: 297,
          usage: "B",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 9,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 10,
          rpt: "1",
          table: 200,
          usage: "D",
        },
        {
          hl7Type: "ST",
          length: { max: 4 },
          name: "Identifier Check Digit",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 12,
          rpt: "1",
          table: 61,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 13,
          rpt: "1",
          table: 203,
          usage: "D",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 15,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 16,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 17,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 18,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 19,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 20,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 22,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 23,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 24,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 25,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "XCN",
      name: "Override Entered By",
      num: 4,
      usage: {
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Person Identifier",
          num: 1,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "FN", name: "Family Name", num: 2, rpt: "1", usage: "D" },
        { hl7Type: "ST", name: "Given Name", num: 3, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 7,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "CWE",
          name: "Source Table",
          num: 8,
          rpt: "1",
          table: 297,
          usage: "B",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 9,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 10,
          rpt: "1",
          table: 200,
          usage: "D",
        },
        {
          hl7Type: "ST",
          length: { max: 4 },
          name: "Identifier Check Digit",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 12,
          rpt: "1",
          table: 61,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 13,
          rpt: "1",
          table: 203,
          usage: "D",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 15,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 16,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 17,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 18,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 19,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 20,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 22,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 23,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 24,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 25,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "XCN",
      name: "Override Authorized By",
      num: 5,
      usage: {
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
  ],
  name: "OVR",
  versions: ["2.5", "2.5.1", "2.6", "2.7", "2.7.1", "2.8"],
};
