import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * PCE — Patient Charge Cost Center Exceptions
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/PCE)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const PCE_SPEC: SegmentSpec = {
  description: "Patient Charge Cost Center Exceptions",
  fields: [
    {
      hl7Type: "SI",
      length: { max: 4 },
      name: "Set Id - Pce",
      num: 1,
      usage: { "2.6": "R", "2.7": "R", "2.7.1": "R", "2.8": "R" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Id Number", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ST",
          name: "Identifier Check Digit",
          num: 2,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 3,
          rpt: "1",
          table: 61,
          usage: "O",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 4,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 5,
          rpt: "1",
          table: 203,
          usage: "R",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "DT", name: "Effective Date", num: 7, rpt: "1", usage: "O" },
        {
          hl7Type: "DT",
          name: "Expiration Date",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 9,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 10,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 12,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "CX",
      name: "Cost Center Account Number",
      num: 2,
      table: 319,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Transaction Code",
      num: 3,
      table: 132,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "MO", name: "Price", num: 1, rpt: "1", usage: "R" },
        {
          hl7Type: "ID",
          length: { max: 2 },
          name: "Price Type",
          num: 2,
          rpt: "1",
          table: 205,
          usage: "O",
        },
        { hl7Type: "NM", name: "From Value", num: 3, rpt: "1", usage: "O" },
        { hl7Type: "NM", name: "To Value", num: 4, rpt: "1", usage: "O" },
        { hl7Type: "CWE", name: "Range Units", num: 5, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Range Type",
          num: 6,
          rpt: "1",
          table: 298,
          usage: "O",
        },
      ],
      hl7Type: "CP",
      name: "Transaction Amount - Unit",
      num: 4,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
  ],
  name: "PCE",
  versions: ["2.6", "2.7", "2.7.1", "2.8"],
};
