import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * PEO — Product Experience Observation
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/PEO)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const PEO_SPEC: SegmentSpec = {
  name: "PEO",
  description: "Product Experience Observation",
  versions: ["2.3","2.3.1","2.4","2.5","2.5.1","2.6","2.7","2.7.1","2.8"],
  fields: [
    {
      num: 1,
      name: "Event Identifiers Used",
      hl7Type: "CWE",
      table: 9999,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
      components: [
        { num: 1, name: "Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 2, name: "Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 3, name: "Name Of Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 4, name: "Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 5, name: "Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 6, name: "Name Of Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 7, name: "Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 8, name: "Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 9, name: "Original Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 10, name: "Second Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 11, name: "Second Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 12, name: "Name Of Second Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 13, name: "Second Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 14, name: "Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 15, name: "Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 16, name: "Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
        { num: 17, name: "Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 18, name: "Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 19, name: "Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
        { num: 20, name: "Second Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 21, name: "Second Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 22, name: "Second Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
      ],
    },
    {
      num: 2,
      name: "Event Symptom/Diagnosis Code",
      hl7Type: "CWE",
      table: 9999,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
      components: [
        { num: 1, name: "Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 2, name: "Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 3, name: "Name Of Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 4, name: "Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 5, name: "Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 6, name: "Name Of Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 7, name: "Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 8, name: "Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 9, name: "Original Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 10, name: "Second Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 11, name: "Second Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 12, name: "Name Of Second Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 13, name: "Second Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 14, name: "Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 15, name: "Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 16, name: "Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
        { num: 17, name: "Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 18, name: "Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 19, name: "Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
        { num: 20, name: "Second Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 21, name: "Second Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 22, name: "Second Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
      ],
    },
    {
      num: 3,
      name: "Event Onset Date/Time",
      hl7Type: "DTM",
      usage: {"2.3":"R","2.3.1":"R","2.4":"R","2.5":"R","2.5.1":"R","2.6":"R","2.7":"R","2.7.1":"R","2.8":"R"},
    },
    {
      num: 4,
      name: "Event Exacerbation Date/Time",
      hl7Type: "DTM",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 5,
      name: "Event Improved Date/Time",
      hl7Type: "DTM",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 6,
      name: "Event Ended Data/Time",
      hl7Type: "DTM",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 7,
      name: "Event Location Occurred Address",
      hl7Type: "XAD",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
      components: [
        { num: 1, name: "Street Address", hl7Type: "SAD", usage: "O", rpt: "1" },
        { num: 2, name: "Other Designation", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 3, name: "City", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 4, name: "State Or Province", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 5, name: "Zip Or Postal Code", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 6, name: "Country", hl7Type: "ID", length: { max: 3 }, table: 399, usage: "O", rpt: "1" },
        { num: 7, name: "Address Type", hl7Type: "ID", length: { max: 3 }, table: 190, usage: "D", rpt: "1" },
        { num: 8, name: "Other Geographic Designation", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 9, name: "County/Parish Code", hl7Type: "CWE", table: 289, usage: "O", rpt: "1" },
        { num: 10, name: "Census Tract", hl7Type: "CWE", table: 288, usage: "O", rpt: "1" },
        { num: 11, name: "Address Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
        { num: 12, name: "Address Validity Range", hl7Type: "ST", usage: "W", rpt: "1" },
        { num: 13, name: "Effective Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 14, name: "Expiration Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 15, name: "Expiration Reason", hl7Type: "CWE", table: 616, usage: "O", rpt: "1" },
        { num: 16, name: "Temporary Indicator", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "O", rpt: "1" },
        { num: 17, name: "Bad Address Indicator", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "O", rpt: "1" },
        { num: 18, name: "Address Usage", hl7Type: "ID", length: { max: 1 }, table: 617, usage: "O", rpt: "1" },
        { num: 19, name: "Addressee", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 20, name: "Comment", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 21, name: "Preference Order", hl7Type: "NM", usage: "O", rpt: "1" },
        { num: 22, name: "Protection Code", hl7Type: "CWE", table: 618, usage: "O", rpt: "1" },
        { num: 23, name: "Address Identifier", hl7Type: "EI", usage: "O", rpt: "1" },
      ],
    },
    {
      num: 8,
      name: "Event Qualification",
      hl7Type: "ID",
      length: { max: 1 },
      table: 237,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 9,
      name: "Event Serious",
      hl7Type: "ID",
      length: { max: 1 },
      table: 238,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 10,
      name: "Event Expected",
      hl7Type: "ID",
      length: { max: 1 },
      table: 239,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 11,
      name: "Event Outcome",
      hl7Type: "ID",
      length: { max: 1 },
      table: 240,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 12,
      name: "Patient Outcome",
      hl7Type: "ID",
      length: { max: 1 },
      table: 241,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 13,
      name: "Event Description From Others",
      hl7Type: "FT",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 14,
      name: "Event Description From Original Reporter",
      hl7Type: "FT",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 15,
      name: "Event Description From Patient",
      hl7Type: "FT",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 16,
      name: "Event Description From Practitioner",
      hl7Type: "FT",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 17,
      name: "Event Description From Autopsy",
      hl7Type: "FT",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 18,
      name: "Cause Of Death",
      hl7Type: "CWE",
      table: 9999,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
      components: [
        { num: 1, name: "Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 2, name: "Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 3, name: "Name Of Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 4, name: "Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 5, name: "Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 6, name: "Name Of Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 7, name: "Coding System Version Id", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 8, name: "Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 9, name: "Original Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 10, name: "Second Alternate Identifier", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 11, name: "Second Alternate Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 12, name: "Name Of Second Alternate Coding System", hl7Type: "ID", length: { max: 12 }, table: 396, usage: "D", rpt: "1" },
        { num: 13, name: "Second Alternate Coding System Version Id", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 14, name: "Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 15, name: "Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 16, name: "Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
        { num: 17, name: "Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 18, name: "Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 19, name: "Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
        { num: 20, name: "Second Alternate Coding System Oid", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 21, name: "Second Alternate Value Set Oid", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 22, name: "Second Alternate Value Set Version Id", hl7Type: "DTM", usage: "D", rpt: "1" },
      ],
    },
    {
      num: 19,
      name: "Primary Observer Name",
      hl7Type: "XPN",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
      components: [
        { num: 1, name: "Family Name", hl7Type: "FN", rpt: "1" },
        { num: 2, name: "Given Name", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 3, name: "Second And Further Given Names Or Initials Thereof", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 4, name: "Suffix (e.g., Jr Or Iii)", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 5, name: "Prefix (e.g., Dr)", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 6, name: "Degree (e.g., Md)", hl7Type: "ST", usage: "W", rpt: "1" },
        { num: 7, name: "Name Type Code", hl7Type: "ID", length: { max: 5 }, table: 200, usage: "O", rpt: "1" },
        { num: 8, name: "Name Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
        { num: 9, name: "Name Context", hl7Type: "CWE", table: 448, usage: "O", rpt: "1" },
        { num: 10, name: "Name Validity Range", hl7Type: "ST", usage: "W", rpt: "1" },
        { num: 11, name: "Name Assembly Order", hl7Type: "ID", length: { max: 1 }, table: 444, usage: "O", rpt: "1" },
        { num: 12, name: "Effective Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 13, name: "Expiration Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 14, name: "Professional Suffix", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 15, name: "Called By", hl7Type: "ST", usage: "O", rpt: "1" },
      ],
    },
    {
      num: 20,
      name: "Primary Observer Address",
      hl7Type: "XAD",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
      components: [
        { num: 1, name: "Street Address", hl7Type: "SAD", usage: "O", rpt: "1" },
        { num: 2, name: "Other Designation", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 3, name: "City", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 4, name: "State Or Province", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 5, name: "Zip Or Postal Code", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 6, name: "Country", hl7Type: "ID", length: { max: 3 }, table: 399, usage: "O", rpt: "1" },
        { num: 7, name: "Address Type", hl7Type: "ID", length: { max: 3 }, table: 190, usage: "D", rpt: "1" },
        { num: 8, name: "Other Geographic Designation", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 9, name: "County/Parish Code", hl7Type: "CWE", table: 289, usage: "O", rpt: "1" },
        { num: 10, name: "Census Tract", hl7Type: "CWE", table: 288, usage: "O", rpt: "1" },
        { num: 11, name: "Address Representation Code", hl7Type: "ID", length: { max: 1 }, table: 465, usage: "O", rpt: "1" },
        { num: 12, name: "Address Validity Range", hl7Type: "ST", usage: "W", rpt: "1" },
        { num: 13, name: "Effective Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 14, name: "Expiration Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 15, name: "Expiration Reason", hl7Type: "CWE", table: 616, usage: "O", rpt: "1" },
        { num: 16, name: "Temporary Indicator", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "O", rpt: "1" },
        { num: 17, name: "Bad Address Indicator", hl7Type: "ID", length: { max: 1 }, table: 136, usage: "O", rpt: "1" },
        { num: 18, name: "Address Usage", hl7Type: "ID", length: { max: 1 }, table: 617, usage: "O", rpt: "1" },
        { num: 19, name: "Addressee", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 20, name: "Comment", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 21, name: "Preference Order", hl7Type: "NM", usage: "O", rpt: "1" },
        { num: 22, name: "Protection Code", hl7Type: "CWE", table: 618, usage: "O", rpt: "1" },
        { num: 23, name: "Address Identifier", hl7Type: "EI", usage: "O", rpt: "1" },
      ],
    },
    {
      num: 21,
      name: "Primary Observer Telephone",
      hl7Type: "XTN",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
      components: [
        { num: 1, name: "Telephone Number", hl7Type: "ST", usage: "W", rpt: "1" },
        { num: 2, name: "Telecommunication Use Code", hl7Type: "ID", length: { max: 3 }, table: 201, usage: "O", rpt: "1" },
        { num: 3, name: "Telecommunication Equipment Type", hl7Type: "ID", length: { max: 8 }, table: 202, usage: "R", rpt: "1" },
        { num: 4, name: "Communication Address", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 5, name: "Country Code", hl7Type: "SNM", usage: "O", rpt: "1" },
        { num: 6, name: "Area/City Code", hl7Type: "SNM", usage: "O", rpt: "1" },
        { num: 7, name: "Local Number", hl7Type: "SNM", usage: "D", rpt: "1" },
        { num: 8, name: "Extension", hl7Type: "SNM", usage: "D", rpt: "1" },
        { num: 9, name: "Any Text", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 10, name: "Extension Prefix", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 11, name: "Speed Dial Code", hl7Type: "ST", usage: "O", rpt: "1" },
        { num: 12, name: "Unformatted Telephone Number", hl7Type: "ST", usage: "D", rpt: "1" },
        { num: 13, name: "Effective Start Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 14, name: "Expiration Date", hl7Type: "DTM", usage: "O", rpt: "1" },
        { num: 15, name: "Expiration Reason", hl7Type: "CWE", table: 868, usage: "O", rpt: "1" },
        { num: 16, name: "Protection Code", hl7Type: "CWE", table: 618, usage: "O", rpt: "1" },
        { num: 17, name: "Shared Telecommunication Identifier", hl7Type: "EI", usage: "O", rpt: "1" },
        { num: 18, name: "Preference Order", hl7Type: "NM", usage: "O", rpt: "1" },
      ],
    },
    {
      num: 22,
      name: "Primary Observer's Qualification",
      hl7Type: "ID",
      length: { max: 1 },
      table: 242,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 23,
      name: "Confirmation Provided By",
      hl7Type: "ID",
      length: { max: 1 },
      table: 242,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 24,
      name: "Primary Observer Aware Date/Time",
      hl7Type: "DTM",
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
    {
      num: 25,
      name: "Primary Observer's Identity May Be Divulged",
      hl7Type: "ID",
      length: { max: 2 },
      table: 243,
      usage: {"2.3":"O","2.3.1":"O","2.4":"O","2.5":"O","2.5.1":"O","2.6":"O","2.7":"O","2.7.1":"O","2.8":"O"},
    },
  ],
};
