/*
MIT License

Copyright (c) 2026 Shane

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * RF1 — Referral Information
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/RF1)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const RF1_SPEC: SegmentSpec = {
  description: "Referral Information",
  fields: [
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Referral Status",
      num: 1,
      table: 283,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Referral Priority",
      num: 2,
      table: 280,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Referral Type",
      num: 3,
      table: 281,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Referral Disposition",
      num: 4,
      table: 282,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Referral Category",
      num: 5,
      table: 284,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "Originating Referral Identifier",
      num: 6,
      usage: {
        "2.3": "R",
        "2.3.1": "R",
        "2.4": "R",
        "2.5": "R",
        "2.5.1": "R",
        "2.6": "R",
        "2.7": "R",
        "2.7.1": "R",
        "2.8": "R",
      },
    },
    {
      hl7Type: "DTM",
      name: "Effective Date",
      num: 7,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      hl7Type: "DTM",
      name: "Expiration Date",
      num: 8,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      hl7Type: "DTM",
      name: "Process Date",
      num: 9,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Referral Reason",
      num: 10,
      table: 336,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Entity Identifier",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "IS",
          name: "Namespace Id",
          num: 2,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        { hl7Type: "ST", name: "Universal Id", num: 3, rpt: "1", usage: "D" },
        {
          hl7Type: "ID",
          length: { max: 6 },
          name: "Universal Id Type",
          num: 4,
          rpt: "1",
          table: 301,
          usage: "D",
        },
      ],
      hl7Type: "EI",
      name: "External Referral Identifier",
      num: 11,
      usage: {
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "O",
        "2.7.1": "O",
        "2.8": "O",
      },
    },
    {
      components: [
        { hl7Type: "ST", name: "Identifier", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "ST", name: "Text", num: 2, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Coding System",
          num: 3,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Identifier",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Alternate Text", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Alternate Coding System",
          num: 6,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Coding System Version Id",
          num: 7,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Version Id",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "ST", name: "Original Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second Alternate Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Text",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 12 },
          name: "Name Of Second Alternate Coding System",
          num: 12,
          rpt: "1",
          table: 396,
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Version Id",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Coding System Oid",
          num: 14,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "ST", name: "Value Set Oid", num: 15, rpt: "1", usage: "O" },
        {
          hl7Type: "DTM",
          name: "Value Set Version Id",
          num: 16,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Coding System Oid",
          num: 17,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Alternate Value Set Oid",
          num: 18,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Alternate Value Set Version Id",
          num: 19,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Coding System Oid",
          num: 20,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Second Alternate Value Set Oid",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Second Alternate Value Set Version Id",
          num: 22,
          rpt: "1",
          usage: "D",
        },
      ],
      hl7Type: "CWE",
      name: "Referral Documentation Completion Status",
      num: 12,
      table: 865,
      usage: { "2.6": "O", "2.7": "O", "2.7.1": "O", "2.8": "O" },
    },
    {
      hl7Type: "DTM",
      length: { max: 24 },
      name: "Planned Treatment Stop Date",
      num: 13,
      usage: { "2.8": "O" },
    },
    {
      hl7Type: "ST",
      length: { max: 60 },
      name: "Referral Reason Text",
      num: 14,
      usage: { "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "NM", name: "Quantity", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "CWE", name: "Units", num: 2, rpt: "1", usage: "O" },
      ],
      hl7Type: "CQ",
      length: { max: 721 },
      name: "Number of Authorized Treatments/Units",
      num: 15,
      usage: { "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "NM", name: "Quantity", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "CWE", name: "Units", num: 2, rpt: "1", usage: "O" },
      ],
      hl7Type: "CQ",
      length: { max: 721 },
      name: "Number of Used Treatments/Units",
      num: 16,
      usage: { "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "NM", name: "Quantity", num: 1, rpt: "1", usage: "O" },
        { hl7Type: "CWE", name: "Units", num: 2, rpt: "1", usage: "O" },
      ],
      hl7Type: "CQ",
      length: { max: 721 },
      name: "Number of Schedule Treatments/Units",
      num: 17,
      usage: { "2.8": "O" },
    },
    {
      components: [
        { hl7Type: "NM", name: "Quantity", num: 1, rpt: "1", usage: "O" },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Denomination",
          num: 2,
          rpt: "1",
          table: 913,
          usage: "O",
        },
      ],
      hl7Type: "MO",
      length: { max: 20 },
      name: "Remaining Benefit Amount",
      num: 18,
      usage: { "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Organization Name",
          num: 1,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Organization Name Type Code",
          num: 2,
          rpt: "1",
          table: 204,
          usage: "O",
        },
        { hl7Type: "ST", name: "Id Number", num: 3, rpt: "1", usage: "W" },
        {
          hl7Type: "ST",
          name: "Identifier Check Digit",
          num: 4,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ST",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 5,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 6,
          rpt: "1",
          table: 363,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 7,
          rpt: "1",
          table: 203,
          usage: "O",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 8,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 9,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Organization Identifier",
          num: 10,
          rpt: "1",
          usage: "O",
        },
      ],
      hl7Type: "XON",
      length: { max: 250 },
      name: "Authorized Provider",
      num: 19,
      usage: { "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Person Identifier",
          num: 1,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "FN", name: "Family Name", num: 2, rpt: "1", usage: "D" },
        { hl7Type: "ST", name: "Given Name", num: 3, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Second And Further Given Names Or Initials Thereof",
          num: 4,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Suffix (e.g., Jr Or Iii)",
          num: 5,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Prefix (e.g., Dr)",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Degree (e.g., Md)",
          num: 7,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "CWE",
          name: "Source Table",
          num: 8,
          rpt: "1",
          table: 297,
          usage: "B",
        },
        {
          hl7Type: "HD",
          name: "Assigning Authority",
          num: 9,
          rpt: "1",
          table: 363,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Name Type Code",
          num: 10,
          rpt: "1",
          table: 200,
          usage: "D",
        },
        {
          hl7Type: "ST",
          length: { max: 4 },
          name: "Identifier Check Digit",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Check Digit Scheme",
          num: 12,
          rpt: "1",
          table: 61,
          usage: "D",
        },
        {
          hl7Type: "ID",
          length: { max: 5 },
          name: "Identifier Type Code",
          num: 13,
          rpt: "1",
          table: 203,
          usage: "D",
        },
        {
          hl7Type: "HD",
          name: "Assigning Facility",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Representation Code",
          num: 15,
          rpt: "1",
          table: 465,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Name Context",
          num: 16,
          rpt: "1",
          table: 448,
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Name Validity Range",
          num: 17,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 1 },
          name: "Name Assembly Order",
          num: 18,
          rpt: "1",
          table: 444,
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Effective Date",
          num: 19,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 20,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Professional Suffix",
          num: 21,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Jurisdiction",
          num: 22,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "CWE",
          name: "Assigning Agency Or Department",
          num: 23,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "ST",
          name: "Security Check",
          num: 24,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Security Check Scheme",
          num: 25,
          rpt: "1",
          table: 904,
          usage: "O",
        },
      ],
      hl7Type: "XCN",
      length: { max: 250 },
      name: "Authorized Health Professional",
      num: 20,
      usage: { "2.8": "O" },
    },
    {
      hl7Type: "ST",
      length: { max: 60 },
      name: "Source Text",
      num: 21,
      usage: { "2.8": "O" },
    },
    {
      hl7Type: "DTM",
      length: { max: 24 },
      name: "Source Date",
      num: 22,
      usage: { "2.8": "O" },
    },
    {
      components: [
        {
          hl7Type: "ST",
          name: "Telephone Number",
          num: 1,
          rpt: "1",
          usage: "W",
        },
        {
          hl7Type: "ID",
          length: { max: 3 },
          name: "Telecommunication Use Code",
          num: 2,
          rpt: "1",
          table: 201,
          usage: "O",
        },
        {
          hl7Type: "ID",
          length: { max: 8 },
          name: "Telecommunication Equipment Type",
          num: 3,
          rpt: "1",
          table: 202,
          usage: "R",
        },
        {
          hl7Type: "ST",
          name: "Communication Address",
          num: 4,
          rpt: "1",
          usage: "D",
        },
        { hl7Type: "SNM", name: "Country Code", num: 5, rpt: "1", usage: "O" },
        {
          hl7Type: "SNM",
          name: "Area/City Code",
          num: 6,
          rpt: "1",
          usage: "O",
        },
        { hl7Type: "SNM", name: "Local Number", num: 7, rpt: "1", usage: "D" },
        { hl7Type: "SNM", name: "Extension", num: 8, rpt: "1", usage: "D" },
        { hl7Type: "ST", name: "Any Text", num: 9, rpt: "1", usage: "O" },
        {
          hl7Type: "ST",
          name: "Extension Prefix",
          num: 10,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Speed Dial Code",
          num: 11,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "ST",
          name: "Unformatted Telephone Number",
          num: 12,
          rpt: "1",
          usage: "D",
        },
        {
          hl7Type: "DTM",
          name: "Effective Start Date",
          num: 13,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "DTM",
          name: "Expiration Date",
          num: 14,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Expiration Reason",
          num: 15,
          rpt: "1",
          table: 868,
          usage: "O",
        },
        {
          hl7Type: "CWE",
          name: "Protection Code",
          num: 16,
          rpt: "1",
          table: 618,
          usage: "O",
        },
        {
          hl7Type: "EI",
          name: "Shared Telecommunication Identifier",
          num: 17,
          rpt: "1",
          usage: "O",
        },
        {
          hl7Type: "NM",
          name: "Preference Order",
          num: 18,
          rpt: "1",
          usage: "O",
        },
      ],
      hl7Type: "XTN",
      length: { max: 250 },
      name: "Source Phone",
      num: 23,
      usage: { "2.8": "O" },
    },
    {
      hl7Type: "ST",
      length: { max: 250 },
      name: "Comment",
      num: 24,
      usage: { "2.8": "O" },
    },
    {
      hl7Type: "ID",
      length: { max: 1 },
      name: "Action Code",
      num: 25,
      table: 206,
      usage: { "2.8": "O" },
    },
  ],
  name: "RF1",
  versions: [
    "2.3",
    "2.3.1",
    "2.4",
    "2.5",
    "2.5.1",
    "2.6",
    "2.7",
    "2.7.1",
    "2.8",
  ],
};
