import { SegmentSpec } from "@/hl7/metadata/types";

/**
 * UB1 — Ub82
 *
 * Generated from the Caristix HL7 Definition API
 * (https://hl7-definition.caristix.com/v2/HL7v2.X/Segments/UB1)
 * by scripts/generate-segment-specs.mjs. Do not edit by hand — re-run the
 * generator instead.
 *
 * @since 4.0.0
 */
export const UB1_SPEC: SegmentSpec = {
  description: "Ub82",
  fields: [
    {
      hl7Type: "ST",
      name: "Set Id - Ub1",
      num: 1,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Blood Deductible",
      num: 2,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "B",
        "2.3.1": "B",
        "2.4": "B",
        "2.5": "B",
        "2.5.1": "B",
        "2.6": "W",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Blood Furnished-pints",
      num: 3,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Blood Replaced-pints",
      num: 4,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Blood Not Replaced-pints",
      num: 5,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Co-insurance Days",
      num: 6,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Condition Code",
      num: 7,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Covered Days",
      num: 8,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Non Covered Days",
      num: 9,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Value Amount & Code",
      num: 10,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Number Of Grace Days",
      num: 11,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Special Program Indicator",
      num: 12,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Psro/Ur Approval Indicator",
      num: 13,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Psro/Ur Approved Stay-fm",
      num: 14,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Psro/Ur Approved Stay-to",
      num: 15,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "O",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Occurrence",
      num: 16,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Occurrence Span",
      num: 17,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Occur Span Start Date",
      num: 18,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Occur Span End Date",
      num: 19,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "O",
        "2.5": "O",
        "2.5.1": "O",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Ub-82 Locator 2",
      num: 20,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "B",
        "2.5": "B",
        "2.5.1": "B",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Ub-82 Locator 9",
      num: 21,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "B",
        "2.5": "B",
        "2.5.1": "B",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Ub-82 Locator 27",
      num: 22,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "B",
        "2.5": "B",
        "2.5.1": "B",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
    {
      hl7Type: "ST",
      name: "Ub-82 Locator 45",
      num: 23,
      usage: {
        "2.1": "O",
        "2.2": "O",
        "2.3": "O",
        "2.3.1": "O",
        "2.4": "B",
        "2.5": "B",
        "2.5.1": "B",
        "2.6": "B",
        "2.7": "W",
        "2.7.1": "W",
        "2.8": "W",
      },
    },
  ],
  name: "UB1",
  versions: [
    "2.1",
    "2.2",
    "2.3",
    "2.3.1",
    "2.4",
    "2.5",
    "2.5.1",
    "2.6",
    "2.7",
    "2.7.1",
    "2.8",
  ],
};
